
package ar.com.zeni.zeniadminwsdl;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.6.1
 * 2012-11-23T15:17:13.896-03:00
 * Generated source version: 2.6.1
 */

@WebFault(name = "FaultType", targetNamespace = "http://www.zeni.com.ar/ZeniAdminWSDL/")
public class FaultType_Exception extends Exception {
	private static final long	serialVersionUID	= 2354112345987751L;
	private FaultType faultType;

    public FaultType_Exception() {
        super();
    }
    
    public FaultType_Exception(String message) {
        super(message);
    }
    
    public FaultType_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public FaultType_Exception(String message, FaultType faultType) {
        super(message);
        this.faultType = faultType;
    }

    public FaultType_Exception(String message, FaultType faultType, Throwable cause) {
        super(message, cause);
        this.faultType = faultType;
    }

    public FaultType getFaultInfo() {
        return this.faultType;
    }
}
