
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package ar.com.zeni.zeniadminwsdl;

import ar.com.zeni.admin.app.server.ZeniViewert;


/**
 * This class was generated by Apache CXF 2.6.1
 * 2012-11-23T15:17:13.931-03:00
 * Generated source version: 2.6.1
 * 
 */

@javax.jws.WebService(
                      serviceName = "ZeniAdminWSDL",
                      portName = "ZeniAdminWSDLSOAP",
                      targetNamespace = "http://www.zeni.com.ar/ZeniAdminWSDL/",
                      wsdlLocation = "http://localhost:8888/jaxzeniadminimpl/services/ZeniAdminWSDLSOAP?wsdl",
                      endpointInterface = "ar.com.zeni.zeniadminwsdl.ZeniAdminWSDL")
                      
public class ZeniAdminWSDLImpl extends ZeniViewert implements ar.com.zeni.zeniadminwsdl.ZeniAdminWSDL {

}
