package ar.com.zeni.zeniadminwsdl;

import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by Apache CXF 2.6.1
 * 2018-10-30T10:44:15.979-03:00
 * Generated source version: 2.6.1
 *
 */
@WebServiceClient(name = "ZeniAdminWSDL",
                  wsdlLocation = "ZeniAdminWSDL.wsdl",
                  targetNamespace = "http://www.zeni.com.ar/ZeniAdminWSDL/")
public class ZeniAdminWSDL_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.zeni.com.ar/ZeniAdminWSDL/", "ZeniAdminWSDL");
    public final static QName ZeniAdminWSDLSOAP = new QName("http://www.zeni.com.ar/ZeniAdminWSDL/", "ZeniAdminWSDLSOAP");
    static {
        URL url = ZeniAdminWSDL_Service.class.getResource("ZeniAdminWSDL.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(ZeniAdminWSDL_Service.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "ZeniAdminWSDL.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ZeniAdminWSDL_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ZeniAdminWSDL_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ZeniAdminWSDL_Service() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     *
     * @return
     *     returns ZeniAdminWSDL
     */
    @WebEndpoint(name = "ZeniAdminWSDLSOAP")
    public ZeniAdminWSDL getZeniAdminWSDLSOAP() {
        return super.getPort(ZeniAdminWSDLSOAP, ZeniAdminWSDL.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ZeniAdminWSDL
     */
    @WebEndpoint(name = "ZeniAdminWSDLSOAP")
    public ZeniAdminWSDL getZeniAdminWSDLSOAP(WebServiceFeature... features) {
        return super.getPort(ZeniAdminWSDLSOAP, ZeniAdminWSDL.class, features);
    }

}
