package ar.com.zeni.zeniadminwsdl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.1
 * 2018-10-30T10:44:15.954-03:00
 * Generated source version: 2.6.1
 *
 */
@WebService(targetNamespace = "http://www.zeni.com.ar/ZeniAdminWSDL/", name = "ZeniAdminWSDL")
@XmlSeeAlso({ObjectFactory.class})
public interface ZeniAdminWSDL {

    @WebResult(name = "out", targetNamespace = "")
    @RequestWrapper(localName = "addUsuario", targetNamespace = "http://www.zeni.com.ar/ZeniAdminWSDL/", className = "ar.com.zeni.zeniadminwsdl.AddUsuario")
    @WebMethod(action = "http://www.zeni.com.ar/ZeniAdminWSDL/addUsuario")
    @ResponseWrapper(localName = "addUsuarioResponse", targetNamespace = "http://www.zeni.com.ar/ZeniAdminWSDL/", className = "ar.com.zeni.zeniadminwsdl.AddUsuarioResponse")
    public java.lang.String addUsuario(
        @WebParam(name = "clienteId", targetNamespace = "")
        java.lang.String clienteId,
        @WebParam(name = "username", targetNamespace = "")
        java.lang.String username,
        @WebParam(name = "name", targetNamespace = "")
        java.lang.String name,
        @WebParam(name = "lastName", targetNamespace = "")
        java.lang.String lastName,
        @WebParam(name = "email", targetNamespace = "")
        java.lang.String email
    ) throws FaultType_Exception;

    @WebResult(name = "out", targetNamespace = "")
    @RequestWrapper(localName = "delNovedad", targetNamespace = "http://www.zeni.com.ar/ZeniAdminWSDL/", className = "ar.com.zeni.zeniadminwsdl.DelNovedad")
    @WebMethod(action = "http://www.zeni.com.ar/ZeniAdminWSDL/delNovedad")
    @ResponseWrapper(localName = "delNovedadResponse", targetNamespace = "http://www.zeni.com.ar/ZeniAdminWSDL/", className = "ar.com.zeni.zeniadminwsdl.DelNovedadResponse")
    public java.lang.String delNovedad(
        @WebParam(name = "idNovedad", targetNamespace = "")
        java.lang.String idNovedad
    ) throws FaultType_Exception;

    @WebResult(name = "out", targetNamespace = "")
    @RequestWrapper(localName = "modNormCrom", targetNamespace = "http://www.zeni.com.ar/ZeniAdminWSDL/", className = "ar.com.zeni.zeniadminwsdl.ModNormCrom")
    @WebMethod(action = "http://www.zeni.com.ar/ZeniAdminWSDL/modNormCrom")
    @ResponseWrapper(localName = "modNormCromResponse", targetNamespace = "http://www.zeni.com.ar/ZeniAdminWSDL/", className = "ar.com.zeni.zeniadminwsdl.ModNormCromResponse")
    public java.lang.String modNormCrom(
        @WebParam(name = "norm", targetNamespace = "")
        ar.com.zeni.zeniadminwsdl.NormCromType norm
    ) throws FaultType_Exception;

    @WebResult(name = "out", targetNamespace = "")
    @RequestWrapper(localName = "modAyuda", targetNamespace = "http://www.zeni.com.ar/ZeniAdminWSDL/", className = "ar.com.zeni.zeniadminwsdl.ModAyuda")
    @WebMethod(action = "http://www.zeni.com.ar/ZeniAdminWSDL/modAyuda")
    @ResponseWrapper(localName = "modAyudaResponse", targetNamespace = "http://www.zeni.com.ar/ZeniAdminWSDL/", className = "ar.com.zeni.zeniadminwsdl.ModAyudaResponse")
    public java.lang.String modAyuda(
        @WebParam(name = "ayuda", targetNamespace = "")
        ar.com.zeni.zeniadminwsdl.AyudaType ayuda
    ) throws FaultType_Exception;

    @WebResult(name = "out", targetNamespace = "")
    @RequestWrapper(localName = "modCliente", targetNamespace = "http://www.zeni.com.ar/ZeniAdminWSDL/", className = "ar.com.zeni.zeniadminwsdl.ModCliente")
    @WebMethod(action = "http://www.zeni.com.ar/ZeniAdminWSDL/modCliente")
    @ResponseWrapper(localName = "modClienteResponse", targetNamespace = "http://www.zeni.com.ar/ZeniAdminWSDL/", className = "ar.com.zeni.zeniadminwsdl.ModClienteResponse")
    public java.lang.String modCliente(
        @WebParam(name = "clienteId", targetNamespace = "")
        java.lang.String clienteId,
        @WebParam(name = "username", targetNamespace = "")
        java.lang.String username,
        @WebParam(name = "name", targetNamespace = "")
        java.lang.String name,
        @WebParam(name = "lastName", targetNamespace = "")
        java.lang.String lastName,
        @WebParam(name = "email", targetNamespace = "")
        java.lang.String email,
        @WebParam(name = "cuentas", targetNamespace = "")
        ar.com.zeni.zeniadminwsdl.ArrayOfAdminCuentaType cuentas
    ) throws FaultType_Exception;

    @WebResult(name = "out", targetNamespace = "")
    @RequestWrapper(localName = "cloneUsuario", targetNamespace = "http://www.zeni.com.ar/ZeniAdminWSDL/", className = "ar.com.zeni.zeniadminwsdl.CloneUsuario")
    @WebMethod(action = "http://www.zeni.com.ar/ZeniAdminWSDL/cloneUsuario")
    @ResponseWrapper(localName = "cloneUsuarioResponse", targetNamespace = "http://www.zeni.com.ar/ZeniAdminWSDL/", className = "ar.com.zeni.zeniadminwsdl.CloneUsuarioResponse")
    public java.lang.String cloneUsuario(
        @WebParam(name = "clienteId", targetNamespace = "")
        java.lang.String clienteId
    ) throws FaultType_Exception;

    @WebResult(name = "outFile", targetNamespace = "")
    @RequestWrapper(localName = "delFile", targetNamespace = "http://www.zeni.com.ar/ZeniAdminWSDL/", className = "ar.com.zeni.zeniadminwsdl.DelFile")
    @WebMethod(action = "http://www.zeni.com.ar/ZeniAdminWSDL/delFile")
    @ResponseWrapper(localName = "delFileResponse", targetNamespace = "http://www.zeni.com.ar/ZeniAdminWSDL/", className = "ar.com.zeni.zeniadminwsdl.DelFileResponse")
    public java.lang.String delFile(
        @WebParam(name = "fileId", targetNamespace = "")
        java.lang.String fileId
    ) throws FaultType_Exception;

    @WebResult(name = "out", targetNamespace = "")
    @RequestWrapper(localName = "obtCategories", targetNamespace = "http://www.zeni.com.ar/ZeniAdminWSDL/", className = "ar.com.zeni.zeniadminwsdl.ObtCategories")
    @WebMethod(action = "http://www.zeni.com.ar/ZeniAdminWSDL/obtCategories")
    @ResponseWrapper(localName = "obtCategoriesResponse", targetNamespace = "http://www.zeni.com.ar/ZeniAdminWSDL/", className = "ar.com.zeni.zeniadminwsdl.ObtCategoriesResponse")
    public ar.com.zeni.zeniadminwsdl.ArrayOfCategoryType obtCategories(
        @WebParam(name = "catId", targetNamespace = "")
        java.lang.String catId
    ) throws FaultType_Exception;

    @WebResult(name = "out", targetNamespace = "")
    @RequestWrapper(localName = "obtCuentas", targetNamespace = "http://www.zeni.com.ar/ZeniAdminWSDL/", className = "ar.com.zeni.zeniadminwsdl.ObtCuentas")
    @WebMethod(action = "http://www.zeni.com.ar/ZeniAdminWSDL/obtCuentas")
    @ResponseWrapper(localName = "obtCuentasResponse", targetNamespace = "http://www.zeni.com.ar/ZeniAdminWSDL/", className = "ar.com.zeni.zeniadminwsdl.ObtCuentasResponse")
    public ar.com.zeni.zeniadminwsdl.ArrayOfAdminCuentaType obtCuentas(
        @WebParam(name = "clienteId", targetNamespace = "")
        java.lang.String clienteId
    ) throws FaultType_Exception;

    @WebResult(name = "out", targetNamespace = "")
    @RequestWrapper(localName = "delNormCrom", targetNamespace = "http://www.zeni.com.ar/ZeniAdminWSDL/", className = "ar.com.zeni.zeniadminwsdl.DelNormCrom")
    @WebMethod(action = "http://www.zeni.com.ar/ZeniAdminWSDL/delNormCrom")
    @ResponseWrapper(localName = "delNormCromResponse", targetNamespace = "http://www.zeni.com.ar/ZeniAdminWSDL/", className = "ar.com.zeni.zeniadminwsdl.DelNormCromResponse")
    public java.lang.String delNormCrom(
        @WebParam(name = "norm", targetNamespace = "")
        java.lang.String norm
    ) throws FaultType_Exception;

    @WebResult(name = "out", targetNamespace = "")
    @RequestWrapper(localName = "obtNews", targetNamespace = "http://www.zeni.com.ar/ZeniAdminWSDL/", className = "ar.com.zeni.zeniadminwsdl.ObtNews")
    @WebMethod(action = "http://www.zeni.com.ar/ZeniAdminWSDL/obtNews")
    @ResponseWrapper(localName = "obtNewsResponse", targetNamespace = "http://www.zeni.com.ar/ZeniAdminWSDL/", className = "ar.com.zeni.zeniadminwsdl.ObtNewsResponse")
    public ar.com.zeni.zeniadminwsdl.ArrayOfNewsType obtNews(
        @WebParam(name = "newId", targetNamespace = "")
        java.lang.String newId
    ) throws FaultType_Exception;

    @WebResult(name = "out", targetNamespace = "")
    @RequestWrapper(localName = "delAyuda", targetNamespace = "http://www.zeni.com.ar/ZeniAdminWSDL/", className = "ar.com.zeni.zeniadminwsdl.DelAyuda")
    @WebMethod(action = "http://www.zeni.com.ar/ZeniAdminWSDL/delAyuda")
    @ResponseWrapper(localName = "delAyudaResponse", targetNamespace = "http://www.zeni.com.ar/ZeniAdminWSDL/", className = "ar.com.zeni.zeniadminwsdl.DelAyudaResponse")
    public java.lang.String delAyuda(
        @WebParam(name = "ayudaId", targetNamespace = "")
        java.lang.String ayudaId
    ) throws FaultType_Exception;

    @WebResult(name = "out", targetNamespace = "")
    @RequestWrapper(localName = "addNovedad", targetNamespace = "http://www.zeni.com.ar/ZeniAdminWSDL/", className = "ar.com.zeni.zeniadminwsdl.AddNovedad")
    @WebMethod(action = "http://www.zeni.com.ar/ZeniAdminWSDL/addNovedad")
    @ResponseWrapper(localName = "addNovedadResponse", targetNamespace = "http://www.zeni.com.ar/ZeniAdminWSDL/", className = "ar.com.zeni.zeniadminwsdl.AddNovedadResponse")
    public java.lang.String addNovedad(
        @WebParam(name = "in", targetNamespace = "")
        ar.com.zeni.zeniadminwsdl.NovedadType in
    ) throws FaultType_Exception;

    @WebResult(name = "out", targetNamespace = "")
    @RequestWrapper(localName = "modNews", targetNamespace = "http://www.zeni.com.ar/ZeniAdminWSDL/", className = "ar.com.zeni.zeniadminwsdl.ModNews")
    @WebMethod(action = "http://www.zeni.com.ar/ZeniAdminWSDL/modNews")
    @ResponseWrapper(localName = "modNewsResponse", targetNamespace = "http://www.zeni.com.ar/ZeniAdminWSDL/", className = "ar.com.zeni.zeniadminwsdl.ModNewsResponse")
    public java.lang.String modNews(
        @WebParam(name = "news", targetNamespace = "")
        ar.com.zeni.zeniadminwsdl.NewsType news
    ) throws FaultType_Exception;

    @WebResult(name = "out", targetNamespace = "")
    @RequestWrapper(localName = "obtFiles", targetNamespace = "http://www.zeni.com.ar/ZeniAdminWSDL/", className = "ar.com.zeni.zeniadminwsdl.ObtFiles")
    @WebMethod(action = "http://www.zeni.com.ar/ZeniAdminWSDL/obtFiles")
    @ResponseWrapper(localName = "obtFilesResponse", targetNamespace = "http://www.zeni.com.ar/ZeniAdminWSDL/", className = "ar.com.zeni.zeniadminwsdl.ObtFilesResponse")
    public ar.com.zeni.zeniadminwsdl.ArrayOfFilesType obtFiles(
        @WebParam(name = "fileId", targetNamespace = "")
        java.lang.String fileId
    ) throws FaultType_Exception;

    @WebResult(name = "out", targetNamespace = "")
    @RequestWrapper(localName = "addAyuda", targetNamespace = "http://www.zeni.com.ar/ZeniAdminWSDL/", className = "ar.com.zeni.zeniadminwsdl.AddAyuda")
    @WebMethod(action = "http://www.zeni.com.ar/ZeniAdminWSDL/addAyuda")
    @ResponseWrapper(localName = "addAyudaResponse", targetNamespace = "http://www.zeni.com.ar/ZeniAdminWSDL/", className = "ar.com.zeni.zeniadminwsdl.AddAyudaResponse")
    public java.lang.String addAyuda(
        @WebParam(name = "ayuda", targetNamespace = "")
        ar.com.zeni.zeniadminwsdl.AyudaType ayuda
    ) throws FaultType_Exception;

    @WebResult(name = "out", targetNamespace = "")
    @RequestWrapper(localName = "uploadFile", targetNamespace = "http://www.zeni.com.ar/ZeniAdminWSDL/", className = "ar.com.zeni.zeniadminwsdl.UploadFile")
    @WebMethod(action = "http://www.zeni.com.ar/ZeniAdminWSDL/uploadFile")
    @ResponseWrapper(localName = "uploadFileResponse", targetNamespace = "http://www.zeni.com.ar/ZeniAdminWSDL/", className = "ar.com.zeni.zeniadminwsdl.UploadFileResponse")
    public java.lang.String uploadFile(
        @WebParam(name = "file", targetNamespace = "")
        ar.com.zeni.zeniadminwsdl.FileType file,
        @WebParam(name = "category", targetNamespace = "")
        java.lang.String category
    ) throws FaultType_Exception;

    @WebResult(name = "fileId", targetNamespace = "")
    @RequestWrapper(localName = "modFiles", targetNamespace = "http://www.zeni.com.ar/ZeniAdminWSDL/", className = "ar.com.zeni.zeniadminwsdl.ModFiles")
    @WebMethod(action = "http://www.zeni.com.ar/ZeniAdminWSDL/modFiles")
    @ResponseWrapper(localName = "modFilesResponse", targetNamespace = "http://www.zeni.com.ar/ZeniAdminWSDL/", className = "ar.com.zeni.zeniadminwsdl.ModFilesResponse")
    public java.lang.String modFiles(
        @WebParam(name = "file", targetNamespace = "")
        ar.com.zeni.zeniadminwsdl.FilesType file
    ) throws FaultType_Exception;

    @WebResult(name = "clienteComp", targetNamespace = "")
    @RequestWrapper(localName = "obtClienteCompleto", targetNamespace = "http://www.zeni.com.ar/ZeniAdminWSDL/", className = "ar.com.zeni.zeniadminwsdl.ObtClienteCompleto")
    @WebMethod(action = "http://www.zeni.com.ar/ZeniAdminWSDL/obtClienteCompleto")
    @ResponseWrapper(localName = "obtClienteCompletoResponse", targetNamespace = "http://www.zeni.com.ar/ZeniAdminWSDL/", className = "ar.com.zeni.zeniadminwsdl.ObtClienteCompletoResponse")
    public ar.com.zeni.zeniadminwsdl.ClienteCompletoType obtClienteCompleto(
        @WebParam(name = "clienteId", targetNamespace = "")
        java.lang.String clienteId
    ) throws FaultType_Exception;

    @WebResult(name = "out", targetNamespace = "")
    @RequestWrapper(localName = "obtNormCrom", targetNamespace = "http://www.zeni.com.ar/ZeniAdminWSDL/", className = "ar.com.zeni.zeniadminwsdl.ObtNormCrom")
    @WebMethod(action = "http://www.zeni.com.ar/ZeniAdminWSDL/obtNormCrom")
    @ResponseWrapper(localName = "obtNormCromResponse", targetNamespace = "http://www.zeni.com.ar/ZeniAdminWSDL/", className = "ar.com.zeni.zeniadminwsdl.ObtNormCromResponse")
    public ar.com.zeni.zeniadminwsdl.ArrayOfNormCromType obtNormCrom(
        @WebParam(name = "norm", targetNamespace = "")
        java.lang.String norm
    ) throws FaultType_Exception;

    @WebResult(name = "out", targetNamespace = "")
    @RequestWrapper(localName = "delNews", targetNamespace = "http://www.zeni.com.ar/ZeniAdminWSDL/", className = "ar.com.zeni.zeniadminwsdl.DelNews")
    @WebMethod(action = "http://www.zeni.com.ar/ZeniAdminWSDL/delNews")
    @ResponseWrapper(localName = "delNewsResponse", targetNamespace = "http://www.zeni.com.ar/ZeniAdminWSDL/", className = "ar.com.zeni.zeniadminwsdl.DelNewsResponse")
    public java.lang.String delNews(
        @WebParam(name = "newsId", targetNamespace = "")
        java.lang.String newsId
    ) throws FaultType_Exception;

    @WebResult(name = "pass", targetNamespace = "")
    @RequestWrapper(localName = "obtClientes", targetNamespace = "http://www.zeni.com.ar/ZeniAdminWSDL/", className = "ar.com.zeni.zeniadminwsdl.ObtClientes")
    @WebMethod(action = "http://www.zeni.com.ar/ZeniAdminWSDL/obtClientes")
    @ResponseWrapper(localName = "obtClientesResponse", targetNamespace = "http://www.zeni.com.ar/ZeniAdminWSDL/", className = "ar.com.zeni.zeniadminwsdl.ObtClientesResponse")
    public ar.com.zeni.zeniadminwsdl.ArrayOfAdminClienteType obtClientes(
        @WebParam(name = "clienteId", targetNamespace = "")
        java.lang.String clienteId
    ) throws FaultType_Exception;

    @WebResult(name = "file", targetNamespace = "")
    @RequestWrapper(localName = "downloadFile", targetNamespace = "http://www.zeni.com.ar/ZeniAdminWSDL/", className = "ar.com.zeni.zeniadminwsdl.DownloadFile")
    @WebMethod(action = "http://www.zeni.com.ar/ZeniAdminWSDL/downloadFile")
    @ResponseWrapper(localName = "downloadFileResponse", targetNamespace = "http://www.zeni.com.ar/ZeniAdminWSDL/", className = "ar.com.zeni.zeniadminwsdl.DownloadFileResponse")
    public ar.com.zeni.zeniadminwsdl.FileType downloadFile(
        @WebParam(name = "fileId", targetNamespace = "")
        java.lang.String fileId,
        @WebParam(name = "category", targetNamespace = "")
        java.lang.String category
    ) throws FaultType_Exception;

    @WebResult(name = "out", targetNamespace = "")
    @RequestWrapper(localName = "addNews", targetNamespace = "http://www.zeni.com.ar/ZeniAdminWSDL/", className = "ar.com.zeni.zeniadminwsdl.AddNews")
    @WebMethod(action = "http://www.zeni.com.ar/ZeniAdminWSDL/addNews")
    @ResponseWrapper(localName = "addNewsResponse", targetNamespace = "http://www.zeni.com.ar/ZeniAdminWSDL/", className = "ar.com.zeni.zeniadminwsdl.AddNewsResponse")
    public java.lang.String addNews(
        @WebParam(name = "news", targetNamespace = "")
        ar.com.zeni.zeniadminwsdl.NewsType news
    ) throws FaultType_Exception;

    @WebResult(name = "out", targetNamespace = "")
    @RequestWrapper(localName = "obtNovedad", targetNamespace = "http://www.zeni.com.ar/ZeniAdminWSDL/", className = "ar.com.zeni.zeniadminwsdl.ObtNovedad")
    @WebMethod(action = "http://www.zeni.com.ar/ZeniAdminWSDL/obtNovedad")
    @ResponseWrapper(localName = "obtNovedadResponse", targetNamespace = "http://www.zeni.com.ar/ZeniAdminWSDL/", className = "ar.com.zeni.zeniadminwsdl.ObtNovedadResponse")
    public ar.com.zeni.zeniadminwsdl.ArrayOfNovedadType obtNovedad(
        @WebParam(name = "novedadId", targetNamespace = "")
        java.lang.String novedadId
    ) throws FaultType_Exception;

    @WebResult(name = "ayudas", targetNamespace = "")
    @RequestWrapper(localName = "obtAyuda", targetNamespace = "http://www.zeni.com.ar/ZeniAdminWSDL/", className = "ar.com.zeni.zeniadminwsdl.ObtAyuda")
    @WebMethod(action = "http://www.zeni.com.ar/ZeniAdminWSDL/obtAyuda")
    @ResponseWrapper(localName = "obtAyudaResponse", targetNamespace = "http://www.zeni.com.ar/ZeniAdminWSDL/", className = "ar.com.zeni.zeniadminwsdl.ObtAyudaResponse")
    public ar.com.zeni.zeniadminwsdl.ArrayOfAyudaType obtAyuda(
        @WebParam(name = "ayudaId", targetNamespace = "")
        java.lang.String ayudaId
    ) throws FaultType_Exception;

    @WebResult(name = "out", targetNamespace = "")
    @RequestWrapper(localName = "resetPassCliente", targetNamespace = "http://www.zeni.com.ar/ZeniAdminWSDL/", className = "ar.com.zeni.zeniadminwsdl.ResetPassCliente")
    @WebMethod(action = "http://www.zeni.com.ar/ZeniAdminWSDL/resetPassCliente")
    @ResponseWrapper(localName = "resetPassClienteResponse", targetNamespace = "http://www.zeni.com.ar/ZeniAdminWSDL/", className = "ar.com.zeni.zeniadminwsdl.ResetPassClienteResponse")
    public java.lang.String resetPassCliente(
        @WebParam(name = "clienteId", targetNamespace = "")
        java.lang.String clienteId
    ) throws FaultType_Exception;

    @WebResult(name = "out", targetNamespace = "")
    @RequestWrapper(localName = "delCliente", targetNamespace = "http://www.zeni.com.ar/ZeniAdminWSDL/", className = "ar.com.zeni.zeniadminwsdl.DelCliente")
    @WebMethod(action = "http://www.zeni.com.ar/ZeniAdminWSDL/delCliente")
    @ResponseWrapper(localName = "delClienteResponse", targetNamespace = "http://www.zeni.com.ar/ZeniAdminWSDL/", className = "ar.com.zeni.zeniadminwsdl.DelClienteResponse")
    public java.lang.String delCliente(
        @WebParam(name = "clienteId", targetNamespace = "")
        java.lang.String clienteId
    ) throws FaultType_Exception;

    @WebResult(name = "out", targetNamespace = "")
    @RequestWrapper(localName = "addNormCrom", targetNamespace = "http://www.zeni.com.ar/ZeniAdminWSDL/", className = "ar.com.zeni.zeniadminwsdl.AddNormCrom")
    @WebMethod(action = "http://www.zeni.com.ar/ZeniAdminWSDL/addNormCrom")
    @ResponseWrapper(localName = "addNormCromResponse", targetNamespace = "http://www.zeni.com.ar/ZeniAdminWSDL/", className = "ar.com.zeni.zeniadminwsdl.AddNormCromResponse")
    public java.lang.String addNormCrom(
        @WebParam(name = "norm", targetNamespace = "")
        ar.com.zeni.zeniadminwsdl.NormCromType norm
    ) throws FaultType_Exception;

    @WebResult(name = "out", targetNamespace = "")
    @RequestWrapper(localName = "modNovedad", targetNamespace = "http://www.zeni.com.ar/ZeniAdminWSDL/", className = "ar.com.zeni.zeniadminwsdl.ModNovedad")
    @WebMethod(action = "http://www.zeni.com.ar/ZeniAdminWSDL/modNovedad")
    @ResponseWrapper(localName = "modNovedadResponse", targetNamespace = "http://www.zeni.com.ar/ZeniAdminWSDL/", className = "ar.com.zeni.zeniadminwsdl.ModNovedadResponse")
    public java.lang.String modNovedad(
        @WebParam(name = "in", targetNamespace = "")
        ar.com.zeni.zeniadminwsdl.NovedadType in
    ) throws FaultType_Exception;
}
