package ar.com.zeni.test;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.io.FileWriter;
import java.io.PrintWriter;
import java.io.UnsupportedEncodingException;
import java.net.MalformedURLException;
import java.net.URL;
import java.security.NoSuchAlgorithmException;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.concurrent.ArrayBlockingQueue;
import java.util.concurrent.BlockingQueue;
import java.util.concurrent.ThreadPoolExecutor;
import java.util.concurrent.TimeUnit;

import javax.xml.datatype.DatatypeConfigurationException;
import javax.xml.datatype.DatatypeFactory;
import javax.xml.namespace.QName;

import ar.com.zeni.codecs.GenericCodec;
import ar.com.zeni.common.ZeniContextServer;
import ar.com.zeni.zeniwsdl.AnalisisMuestraByContratoType;
import ar.com.zeni.zeniwsdl.ArrayOfAjusteComentarioFijacionByContratoType;
import ar.com.zeni.zeniwsdl.ArrayOfCartaDePorteType;
import ar.com.zeni.zeniwsdl.ArrayOfComentarioComentarioFijacionByContrato;
import ar.com.zeni.zeniwsdl.ArrayOfComentarioFijacionByContratoType;
import ar.com.zeni.zeniwsdl.ArrayOfCupoByContratoType;
import ar.com.zeni.zeniwsdl.ArrayOfDestinoMATType;
import ar.com.zeni.zeniwsdl.ArrayOfEntregaByContratoType;
import ar.com.zeni.zeniwsdl.ArrayOfEntregaCubiertaType;
import ar.com.zeni.zeniwsdl.ArrayOfIdCuenta;
import ar.com.zeni.zeniwsdl.ArrayOfMercadoType;
import ar.com.zeni.zeniwsdl.ArrayOfMermasByEntregaType;
import ar.com.zeni.zeniwsdl.ArrayOfMuestraType;
import ar.com.zeni.zeniwsdl.ArrayOfNormCromType;
import ar.com.zeni.zeniwsdl.ArrayOfOperacionMATType;
import ar.com.zeni.zeniwsdl.ArrayOfProductoMATType;
import ar.com.zeni.zeniwsdl.ArrayOfProductoType;
import ar.com.zeni.zeniwsdl.ArrayOfResumenMATType;
import ar.com.zeni.zeniwsdl.AuthType;
import ar.com.zeni.zeniwsdl.ClienteType;
import ar.com.zeni.zeniwsdl.ContratoType;
import ar.com.zeni.zeniwsdl.CuentaType;
import ar.com.zeni.zeniwsdl.EnumCompraVentaType;
import ar.com.zeni.zeniwsdl.EnumCompradorVendedorType;
import ar.com.zeni.zeniwsdl.EnumEstadoType;
import ar.com.zeni.zeniwsdl.EnumOpcionesListadoEntrega;
import ar.com.zeni.zeniwsdl.EnumSucursalType;
import ar.com.zeni.zeniwsdl.EnumTipoComprobanteType;
import ar.com.zeni.zeniwsdl.EnumTipoConsultaComprobanteType;
import ar.com.zeni.zeniwsdl.EnumTipoOperacionMatType;
import ar.com.zeni.zeniwsdl.EnumTipoOperacionType;
import ar.com.zeni.zeniwsdl.FacturaDetalleType;
import ar.com.zeni.zeniwsdl.FacturaRegistroType;
import ar.com.zeni.zeniwsdl.FacturaType;
import ar.com.zeni.zeniwsdl.FaultType_Exception;
import ar.com.zeni.zeniwsdl.FechaTimeType;
import ar.com.zeni.zeniwsdl.MonedaType;
import ar.com.zeni.zeniwsdl.ObtenerCuentaCorrienteContableType;
import ar.com.zeni.zeniwsdl.RangoFechaType;
import ar.com.zeni.zeniwsdl.SINOType;
import ar.com.zeni.zeniwsdl.StringSHA1BASE64DESType;
import ar.com.zeni.zeniwsdl.ZeniWSDL;
import ar.com.zeni.zeniwsdl.ZeniWSDL_Service;

/**
 * This class was generated by Apache CXF 2.6.1 2012-09-10T15:58:26.966-03:00
 * Generated source version: 2.6.1
 *
 */
public final class TestServices {

	private TestServices() {
	}

	public static void main(String args[]) throws java.lang.Exception {
		int veces = 1;
		final TestCaseComplete[] arr = new TestCaseComplete[veces];
		for (int i = 0; i < veces; i++) {
			// arr[i] = new TestCaseComplete(args, "UsuarioPrueba" + (i),
			// "UsuarioPrueba");
			// arr[i] = new TestCaseComplete(args, "4000", "UsuarioPrueba");
			// arr[i] = new TestCaseComplete(args, "1110", "UsuarioPrueba");
			// arr[i] = new TestCaseComplete(args, "UsuarioPrueba4000",
			// "123456");
			// arr[i] = new TestCaseComplete(args, "UsuarioPrueba3941",
			// "UsuarioPrueba");
			arr[i] = new TestCaseComplete(args, "U2523", "zenizeni");
			// arr[i] = new TestCaseComplete(args, "TestDesa", "15438531");
			// arr[i] = new TestCaseComplete(args, "TestDesa", "86668170");
			// arr[i] = new TestCaseComplete(args, "4000", "64729713");
		}
		BlockingQueue<Runnable> lr = new ArrayBlockingQueue<Runnable>(veces);
		ThreadPoolExecutor tp = new ThreadPoolExecutor(8, 80, 1000,
				TimeUnit.MILLISECONDS, lr);
		tp.allowCoreThreadTimeOut(true);
		Date ini = new Date();
		for (int i = 0; i < veces; i++) {
			final TestCaseComplete pepe = arr[i];
			Runnable r = new Runnable() {
				@Override
				public void run() {
					try {
						// while (true) {
						pepe.start();
						Thread.sleep(1000);
						// }
					} catch (Throwable e1) {
						e1.printStackTrace();
					}
				}
			};
			// Thread.sleep(1000);
			tp.execute(r);
		}
		while (tp.getCompletedTaskCount() < veces) {
			try {
				System.out.println("Hay " + tp.getActiveCount()
						+ " tareas ejecutandose y "
						+ tp.getCompletedTaskCount() + " ejecutadas ");
				tp.awaitTermination(2000, TimeUnit.MILLISECONDS);
			} catch (InterruptedException e) {
				e.printStackTrace();
			}
		}
		Date fini = new Date();
		System.out.println("Start Date    : " + ini);
		System.out.println("End Date      : " + fini);
		System.out.println("----------------------------------");
		System.exit(0);
	}

}

class TestCaseComplete {
	private static final QName SERVICE_NAME = new QName(
			"http://www.zeni.com.ar/ZeniWSDL/", "ZeniWSDL");
	private String[] args;
	private String user;
	private String pass;

	public TestCaseComplete(String args[], String user, String pass) {
		this.args = args;
		this.user = user;
		this.pass = pass;
	}

	public void start() throws DatatypeConfigurationException,
			NoSuchAlgorithmException, UnsupportedEncodingException,
			MalformedURLException {
		// URL wsdlURL = ZeniWSDL_Service.WSDL_LOCATION;
		// URL wsdlURL = new
		// URL("http://10.13.0.15:8080/jaxzeniwsimpl/services/ZeniWSDLSOAP?wsdl");
		// URL wsdlURL = new
		// URL("http://10.13.0.15:8080/jaxzeniwsdesa/services/ZeniWSDLSOAP?wsdl");
		URL wsdlURL = new URL(
				"http://200.45.248.68:8080/jaxzeniwsdesa/services/ZeniWSDLSOAP?wsdl");
		// URL wsdlURL = new
		// URL("http://172.30.200.21:8888/jaxzeniwsimpl/services/ZeniWSDLSOAP?wsdl");
		// URL wsdlURL = new
		// URL("http://localhost:8888/jaxzeniwsimpl/services/ZeniWSDLSOAP?wsdl");
		// URL wsdlURL = new
		// URL("http://localhost:8080/jaxzeniwsimpl/services/ZeniWSDLSOAP?wsdl");
		if (args.length > 0 && args[0] != null
				&& !ZeniContextServer.VACIO.equals(args[0])) {
			File wsdlFile = new File(args[0]);
			try {
				if (wsdlFile.exists()) {
					wsdlURL = wsdlFile.toURI().toURL();
				} else {
					wsdlURL = new URL(args[0]);
				}
			} catch (MalformedURLException e) {
				e.printStackTrace();
			}
		}

		ZeniWSDL_Service ss = new ZeniWSDL_Service(wsdlURL, SERVICE_NAME);
		ZeniWSDL port = ss.getZeniWSDLSOAP();
		String usuario = this.user;
		String password = this.pass;
		AuthType AUTH_GENERAL = new AuthType();
		ClienteType CLIENTE_GENERAL = null;
		CuentaType CUENTA_GENERAL = null;
		RangoFechaType RANGO_DEFECHAS = new ar.com.zeni.zeniwsdl.RangoFechaType();
		FechaTimeType FECHA_TOPE = new FechaTimeType();
		ArrayOfProductoType PRODUCTOS_GENERAL = null;
		String CONTRATO_ID = "5446";
		String COMPROBANTE_ID = "5536";
		String CONTRATO_NRO = "12/39058/8";
		String COMPROBANTE_NRO = "19";
		String ACTIVIDAD_ID = "3973";
		String ENTREGA_ID = "3973";
		String PRODUCTO_ID = "414759";
		String COMPROBANTE_TIPO = "FA";
		EnumTipoConsultaComprobanteType TIPO_CONSULTA_COMP = EnumTipoConsultaComprobanteType.EMITIDO;
		EnumCompradorVendedorType TIPO_COMPRODORVONDODOR = EnumCompradorVendedorType.AMBOS;
		EnumTipoComprobanteType TIPODECOMPROBANTE = EnumTipoComprobanteType.COMPLETO;
		SINOType DESCARGADO = SINOType.INDISTINTO;
		String COTRAPARTE_ID = "";
		String CAMPANIA_ID = "";
		// AUTH_GENERAL.setHash("NmY2ZTA1ZTJiNzJmYTY2OWQ5ZDZiZTQ5Mzc3YWE0OGI1MzRiYzA0ZA==");
		// AUTH_GENERAL.setUser("UsuarioPrueba1");
		// FechaTimeType authValHasta = new FechaTimeType();
		// authValHasta.setFecha(DatatypeFactory.newInstance().newXMLGregorianCalendar("2012-09-10T15:58:27.056-03:00"));
		// AUTH_GENERAL.setValidezHasta(authValHasta);
		FECHA_TOPE.setFecha(javax.xml.datatype.DatatypeFactory.newInstance()
				.newXMLGregorianCalendar("2016-04-14T15:58:27.062-03:00"));
		FechaTimeType RFECDES = new ar.com.zeni.zeniwsdl.FechaTimeType();
		RFECDES.setFecha(DatatypeFactory.newInstance().newXMLGregorianCalendar(
				"2016-04-01T00:00:27.069-03:00"));
		RANGO_DEFECHAS.setDesde(RFECDES);
		RANGO_DEFECHAS.setHasta(FECHA_TOPE);
		MonedaType FILTRO_DE_MONEDA = new MonedaType();
		FILTRO_DE_MONEDA.setId("1717");
		FILTRO_DE_MONEDA.setDescripcion("1717");
		FILTRO_DE_MONEDA.setSimbolo("$");
		FILTRO_DE_MONEDA.setCodigoOnca("01");
		ArrayOfIdCuenta array_cuentas = new ArrayOfIdCuenta();
		StringSHA1BASE64DESType PASSWORD_NUEVO = null;

		{
			System.out.println("Invoking Login...");
			try {
				ar.com.zeni.zeniwsdl.HashNSeedType hashAndSeed = port
						.obtenerHashYSeed();
				// System.out.println("HASH: " + hashAndSeed.getHash());
				// System.out.println("SEED: " + hashAndSeed.getSeed());
				// System.out.println("USER: " + usuario);

				// PASSWORD_NUEVO = port.obtenerStringSHA1BASE64DES("12345678",
				// hashAndSeed.getSeed());
				// PASSWORD_NUEVO =
				// port.obtenerStringSHA1BASE64DES("UsuarioPrueba",
				// hashAndSeed.getSeed());

				// STRICT
				AUTH_GENERAL = port.autorizarUsuario(usuario, hashAndSeed
						.getHash(), GenericCodec.DESencrypt64(GenericCodec
						.stringToBase64(GenericCodec.digestSHA1(password)),
						hashAndSeed.getSeed()));

				// LEASE
				// AUTH_GENERAL = port.autorizarUsuario(usuario,
				// hashAndSeed.getHash(),
				// GenericCodec.stringToBase64(GenericCodec.digestSHA1(password)));

				// SIMPLE
				// AUTH_GENERAL = port.autorizarUsuario(usuario,
				// hashAndSeed.getHash(), GenericCodec.digestSHA1(password));

				// UNACTIVE
				// AUTH_GENERAL = port.autorizarUsuario(usuario,
				// hashAndSeed.getHash(), "WhBva5uRHb/SAAZRAFvM//ngB8E=");
				// System.out.println(AUTH_GENERAL.toString());
			} catch (FaultType_Exception e) {
				System.out
						.println("Expected exception: FaultType has occurred.");
				System.out.println(e.toString());
			}
		}
		// {
		// System.out.println("Invoking resetearPassword...");
		// java.lang.String _resetearPassword_usuario =
		// "_resetearPassword_usuario-1285575766";
		// java.lang.String _resetearPassword_email =
		// "_resetearPassword_email1900143756";
		// java.lang.String _resetearPassword_codigoDeAutorizacion =
		// "_resetearPassword_codigoDeAutorizacion-362709439";
		// try {
		// java.lang.String _resetearPassword__return =
		// port.resetearPassword(_resetearPassword_usuario,
		// _resetearPassword_email, _resetearPassword_codigoDeAutorizacion);
		// System.out.println("resetearPassword.result=" +
		// _resetearPassword__return);
		//
		// } catch (FaultType_Exception e) {
		// System.out.println("Expected exception: FaultType has occurred.");
		// System.out.println(e.toString());
		// }
		// }
		// {
		// System.out.println("Invoking obtenerCodigoDeAutorizacion...");
		// java.lang.String _obtenerCodigoDeAutorizacion_usuario =
		// "_obtenerCodigoDeAutorizacion_usuario-1911153589";
		// java.lang.String _obtenerCodigoDeAutorizacion_email =
		// "_obtenerCodigoDeAutorizacion_email-1314356595";
		// try {
		// java.lang.String _obtenerCodigoDeAutorizacion__return =
		// port.obtenerCodigoDeAutorizacion(_obtenerCodigoDeAutorizacion_usuario,
		// _obtenerCodigoDeAutorizacion_email);
		// System.out.println("obtenerCodigoDeAutorizacion.result=" +
		// _obtenerCodigoDeAutorizacion__return);
		//
		// } catch (FaultType_Exception e) {
		// System.out.println("Expected exception: FaultType has occurred.");
		// System.out.println(e.toString());
		// }
		// }
		// {
		// System.out.println("Invoking actualizarPassword...");
		// ar.com.zeni.zeniwsdl.AuthType _actualizarPassword_auth = new
		// ar.com.zeni.zeniwsdl.AuthType();
		// _actualizarPassword_auth.setHash("Hash1154563835");
		// _actualizarPassword_auth.setUser("User-1055851027");
		// ar.com.zeni.zeniwsdl.FechaTimeType
		// _actualizarPassword_authValidezHasta = new
		// ar.com.zeni.zeniwsdl.FechaTimeType();
		// _actualizarPassword_authValidezHasta.setFecha(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2012-09-10T15:58:27.056-03:00"));
		// _actualizarPassword_auth.setValidezHasta(_actualizarPassword_authValidezHasta);
		// // java.lang.String _actualizarPassword_passwordNuevo =
		// // "_actualizarPassword_passwordNuevo-243783125";
		// try {
		// java.lang.String _actualizarPassword__return =
		// port.actualizarPassword(AUTH_GENERAL,
		// PASSWORD_NUEVO.getStringSHA1BASE64DESBASE64());
		// System.out.println("actualizarPassword.result=" +
		// _actualizarPassword__return);
		//
		// } catch (FaultType_Exception e) {
		// System.out.println("Expected exception: FaultType has occurred.");
		// System.out.println(e.toString());
		// }
		// }
		// {
		// System.out.println("Invoking altaUsuario...");
		// java.lang.String _altaUsuario_clienteId =
		// "_altaUsuario_clienteId-1610734230";
		// java.lang.String _altaUsuario_usuario =
		// "_altaUsuario_usuario1844914567";
		// java.lang.String _altaUsuario_nombre =
		// "_altaUsuario_nombre-1783983386";
		// java.lang.String _altaUsuario_apellido =
		// "_altaUsuario_apellido561786193";
		// java.lang.String _altaUsuario_email = "_altaUsuario_email-980638775";
		// java.lang.String _altaUsuario_password =
		// "_altaUsuario_password825432645";
		// java.lang.String _altaUsuario_codigoDeAutorizacion =
		// "_altaUsuario_codigoDeAutorizacion551462119";
		// java.lang.String _altaUsuario_hash = "_altaUsuario_hash1175268994";
		// try {
		// java.lang.String _altaUsuario__return =
		// port.altaUsuario(_altaUsuario_clienteId, _altaUsuario_usuario,
		// _altaUsuario_nombre, _altaUsuario_apellido, _altaUsuario_email,
		// _altaUsuario_password, _altaUsuario_codigoDeAutorizacion,
		// _altaUsuario_hash);
		// System.out.println("altaUsuario.result=" + _altaUsuario__return);
		// } catch (FaultType_Exception e) {
		// System.out.println("Expected exception: FaultType has occurred.");
		// System.out.println(e.toString());
		// }
		// }
		{
			System.out.println("Invoking obtenerCliente...");
			try {
				CLIENTE_GENERAL = port.obtenerCliente(AUTH_GENERAL);
				CUENTA_GENERAL = CLIENTE_GENERAL.getCuentas().getCuentas()
						.get(0);
				// System.out.println("obtenerCliente.result=" +
				// CLIENTE_GENERAL);

				for (int i = 0; i < CLIENTE_GENERAL.getCuentas().getCuentas()
						.size(); i++) {
					array_cuentas.getCuentas().add(
							CLIENTE_GENERAL.getCuentas().getCuentas().get(i)
									.getId());
				}

				for (int i = 0; i < CLIENTE_GENERAL.getCuentasOF().getCuentas()
						.size(); i++) {
					array_cuentas.getCuentas().add(
							CLIENTE_GENERAL.getCuentasOF().getCuentas().get(i)
									.getId());
				}

			} catch (FaultType_Exception e) {
				System.out
						.println("Expected exception: FaultType has occurred.");
				System.out.println(e.toString());
			}
		}

		// {
		// System.out
		// .println("Invoking obtenerSeguimientoDeBoletoByContrato...");
		// try {
		// SeguimientoDeBoletoByContratoType SEGUIMIENTO_BOLETO;
		// SEGUIMIENTO_BOLETO = port.obtenerSeguimientoDeBoletoByContrato(
		// AUTH_GENERAL, "148318988");
		//
		// for (SeguimientoBoletoType a : SEGUIMIENTO_BOLETO
		// .getSeguimientoboleto().getSeguimientoBoleto()) {
		// System.out.println(a.getEstado());
		// }
		//
		// } catch (FaultType_Exception e) {
		// System.out
		// .println("Expected exception: FaultType has occurred.");
		// System.out.println(e.toString());
		// }
		// }
		//
		// {
		// System.out.println("Invoking obtenerProductos...");
		// try {
		// PRODUCTOS_GENERAL = port.obtenerProductos(AUTH_GENERAL);
		// // System.out.println("obtenerProductos.result=" +
		// // PRODUCTOS_GENERAL);
		//
		// } catch (FaultType_Exception e) {
		// System.out
		// .println("Expected exception: FaultType has occurred.");
		// System.out.println(e.toString());
		// }
		// }

		{
			System.out.println("Invoking obtenerAdministracionGarantias...");
			try {


				ArrayOfIdCuenta ctas = new ArrayOfIdCuenta();
				List<String> ccc = new ArrayList<String>();

				ccc.add("147972603");
				ccc.add("149643330");
				ccc.add("105750162");
				ccc.add("105756589");
				ccc.add("105752763");
				ccc.add("105749427");
				ccc.add("105750699");
				ccc.add("105749527");
				ccc.add("141224994");
				ccc.add("134803560");
				ccc.add("105751728");
				ccc.add("144554363");
				ccc.add("105751185");
				ccc.add("106299873");
				ccc.add("105750140");
				ccc.add("153868825");
				ccc.add("105751117");
				ccc.add("150325227");
				ccc.add("149551701");
				ccc.add("105749882");
				ccc.add("105751427");
				ccc.add("1490461412");

				ctas.getCuentas().addAll(ccc);

				ar.com.zeni.zeniwsdl.ArrayOfAdministracionGarantiaType _obtenerAdministracionGarantias__return = port
						.obtenerAdministracionGarantia(AUTH_GENERAL,
								ctas, null, null, null);

				for (ar.com.zeni.zeniwsdl.AdministracionGarantiaType ag : _obtenerAdministracionGarantias__return
						.getAdministracionGarantia()) {
					ag.getAforo();
					ag.getCantidad();
					ag.getCuentaclienteid();
					ag.getDenominacioncuenta();
					ag.getMercado();
					ag.getPrecio();
					ag.getSimbolo();
				}
			} catch (FaultType_Exception e) {
				System.out
						.println("Expected exception: FaultType has occurred.");
				System.out.println(e.toString());
			}
		}

		{
			System.out.println("Invoking obtenerFacturas...");
			try {
				ar.com.zeni.zeniwsdl.ArrayOfFacturaType _obtenerFacturas__return = port
					.obtenerFacturas(AUTH_GENERAL, array_cuentas,
								RANGO_DEFECHAS);
				FileWriter ffact = null;
				FileWriter fdet = null;
				FileWriter freg = null;

			    PrintWriter pwfact = null;
			    PrintWriter pwdet = null;
			    PrintWriter pwreg = null;

			    ffact = new FileWriter("/wrk/funcional/zeni/zeni-facturas.csv");
			    fdet = new FileWriter("/wrk/funcional/zeni/zeni-detalles.csv");
			    freg = new FileWriter("/wrk/funcional/zeni/zeni-registros.csv");

                pwfact = new PrintWriter(ffact);
                pwdet = new PrintWriter(fdet);
                pwreg = new PrintWriter(freg);


                // Titulos
                StringBuffer st = new StringBuffer("");

				st.append("ID");
				st.append(";");
				st.append("Cotizacion");
				st.append(";");
				st.append("Tipo Cpte.");
				st.append(";");
				st.append("Fecha Cpte.");
				st.append(";");
				st.append("Fecha Acreed. CtaCte");
				st.append(";");
				st.append("Letra Cpte");
				st.append(";");
				st.append("Suc. Cpte");
				st.append(";");
				st.append("Nro. Cpte");
				st.append(";");
				st.append("Signo Iva Base");
				st.append(";");
				st.append("Iva Base");
				st.append(";");
				st.append("Signo Iva No Grav.");
				st.append(";");
				st.append("Iva No Grav.");
				st.append(";");
				st.append("Signo Iva Total");
				st.append(";");
				st.append("IVA");
				st.append(";");
				st.append("Signo Importe");
				st.append(";");
				st.append("Importe");
				st.append(";");
				st.append("Moneda");
				st.append(";");
				st.append("Condicion Cte");
				st.append(";");
				st.append("Cto. Cliente");
				st.append(";");
				st.append("Signo Kgs. Fact");
				st.append(";");
				st.append("Kgs. Fact");
				st.append(";");
				st.append("Precio Cto.");
				st.append(";");
				st.append("CUIT Corredor");
				st.append(";");
				st.append("CUIT Contrapartida");
				st.append(";");
				st.append("Estado");
				st.append(";");
				st.append("Fecha Vto. Cpte.");
				st.append(";");
				st.append("Signo Importe a Cta.");
				st.append(";");
				st.append("Importe a Cta.");
				st.append(";");
				st.append("CAI");
				st.append(";");
				st.append("Fecha Vto. CAI");
				st.append(";");
				st.append("CAE");
				st.append(";");
				st.append("Fecha Vto. CAE");
				st.append(";");
				st.append("COE Fact. Papel");
				pwfact.println(st);

				StringBuffer sdt = new StringBuffer("");
				sdt.append("Id Factura");
				sdt.append(";");
				sdt.append("Concepto");
				sdt.append(";");
				sdt.append("Descripcion");
				sdt.append(";");
				sdt.append("Orden");
				sdt.append(";");
				sdt.append("Importe");
				sdt.append(";");
				sdt.append("Base");
				sdt.append(";");
				sdt.append("Porcentaje");
				pwdet.println(sdt);

				StringBuffer srt = new StringBuffer("");
				srt.append("Id Factura");
				srt.append(";");
				srt.append("Id Registro");
				srt.append(";");
				srt.append("Registro");
				srt.append(";");
				srt.append("Caratula");
				srt.append(";");
				srt.append("Concepto");
				srt.append(";");
				srt.append("Contrato");
				srt.append(";");
				srt.append("Monto");
				srt.append(";");
				srt.append("Porcentaje");
				srt.append(";");
				srt.append("Precio o Prima");
				srt.append(";");
				srt.append("Fecha");
				pwreg.println(srt);

                // Valores

				for (FacturaType f : _obtenerFacturas__return.getFacturas()) {

					StringBuffer s = new StringBuffer("");

					s.append(f.getID());
					s.append(";");
					s.append(f.getCOTIZACION());
					s.append(";");
					s.append(f.getTIPO_CPTE());
					s.append(";");
					s.append(f.getFECHA_CPTE().getFecha().toString());
					s.append(";");
					s.append(f.getFECHA_ACRED_CTACTE().getFecha().toString());
					s.append(";");
					s.append(f.getLETRA_CPTE());
					s.append(";");
					s.append(f.getSUCURSAL_CPTE());
					s.append(";");
					s.append(f.getNUMERO_CPTE());
					s.append(";");
					s.append(f.getSIGNO_IVA_BASE());
					s.append(";");
					s.append(f.getIVA_BASE());
					s.append(";");
					s.append(f.getSIGNO_IVA_NO_GRAVADO());
					s.append(";");
					s.append(f.getIVA_NO_GRAVADO());
					s.append(";");
					s.append(f.getSIGNO_IVA_TOTAL());
					s.append(";");
					s.append(f.getIMPORTEIVA());
					s.append(";");
					s.append(f.getSIGNO_IMPORTE());
					s.append(";");
					s.append(f.getIMPORTE());
					s.append(";");
					s.append(f.getMONEDA());
					s.append(";");
					s.append(f.getCONDICION_CLIENTE());
					s.append(";");
					s.append(f.getCTO_CLIENTE());
					s.append(";");
					s.append(f.getSIGNO_KGS_FACT());
					s.append(";");
					s.append(f.getKGS_FACTURADOS());
					s.append(";");
					s.append(f.getPRECIO_CTO());
					s.append(";");
					s.append(f.getCUIT_CORREDOR());
					s.append(";");
					s.append(f.getCUIT_CONTRA());
					s.append(";");
					s.append(f.getESTADO());
					s.append(";");
					s.append(f.getFECHA_VTO_CPTE().getFecha().toString());
					s.append(";");
					s.append(f.getSIGNO_IMPORTE_A_CTA());
					s.append(";");
					s.append(f.getIMPORTE_A_CTA());
					s.append(";");
					s.append(f.getCAI());
					s.append(";");
					s.append(f.getFECHA_VTO_CAI() != null ? f
							.getFECHA_VTO_CAI().getFecha().toString() : " ");
					s.append(";");
					s.append(f.getCAE());
					s.append(";");
					s.append(f.getFECHA_VTO_CAE() != null ? f
							.getFECHA_VTO_CAE().getFecha().toString() : " ");
					s.append(";");
					s.append(f.getCOEFACTURAPAPEL());
					pwfact.println(s);

					for (FacturaDetalleType tf : f.getDETALLE().getFacturaDetalle()) {
						StringBuffer sd = new StringBuffer("");
						sd.append(f.getID());
						sd.append(";");
						sd.append(tf.getCONCEPTO());
						sd.append(";");
						sd.append(tf.getDESCRIPCION());
						sd.append(";");
						sd.append(tf.getORDEN());
						sd.append(";");
						sd.append(tf.getIMPORTE());
						sd.append(";");
						sd.append(tf.getBASE());
						sd.append(";");
						sd.append(tf.getPORCENTAJE());
						pwdet.println(sd);
					}

					for (FacturaRegistroType fr: f.getREGISTRO().getFacturaRegistro()) {
						StringBuffer sr = new StringBuffer("");
						sr.append(f.getID());
						sr.append(";");
						sr.append(fr.getIDREGISTRO());
						sr.append(";");
						sr.append(fr.getREGISTRO());
						sr.append(";");
						sr.append(fr.getCARATULA());
						sr.append(";");
						sr.append(fr.getCONCEPTO());
						sr.append(";");
						sr.append(fr.getCONTRATO());
						sr.append(";");
						sr.append(fr.getMONTO());
						sr.append(";");
						sr.append(fr.getPORCENTAJE());
						sr.append(";");
						sr.append(fr.getPRECIOOPRIMA());
						sr.append(";");
						sr.append(fr.getFECHA().getFecha().toString());
						pwreg.println(sr);
					}
				}

				ffact.close();
				fdet.close();
				freg.close();

				System.out.println("ARCHIVOS OK");

			} catch (Exception e) {
				System.out
						.println("Expected exception: FaultType has occurred.");
				System.out.println(e.toString());
			}
		}

		// {
		// System.out
		// .println("Invoking obtenerSeguimientoBoletoByContrato...");
		// try {
		// ar.com.zeni.zeniwsdl.SeguimientoDeBoletoByContratoType
		// obtenerSeguimiento = port
		// .obtenerSeguimientoDeBoletoByContrato(AUTH_GENERAL,
		// "33500122");
		//
		// ArrayOfSeguimientoBoletoType seg = obtenerSeguimiento
		// .getSeguimientoboleto();
		//
		// for (SeguimientoBoletoType s : seg.getSeguimientoBoleto()) {
		// s.getEstado();
		// s.getFecha();
		// s.getObservacion();
		// s.getUsuario();
		// }
		//
		// } catch (FaultType_Exception e) {
		// System.out
		// .println("Expected exception: FaultType has occurred.");
		// System.out.println(e.toString());
		// }
		// }

		{
			System.out.println("Invoking obtenerCobranzas...");
			ar.com.zeni.zeniwsdl.EnumOperacionesType _obtenerCobranzas_filtroOperaciones = ar.com.zeni.zeniwsdl.EnumOperacionesType.TODAS;
			try {
				// CUENTA_GENERAL.setId("48428");
				ar.com.zeni.zeniwsdl.ArrayOfCobranzaType _obtenerCobranzas__return = port
						.obtenerCobranzas(AUTH_GENERAL, array_cuentas,
								FECHA_TOPE, _obtenerCobranzas_filtroOperaciones);
				// CUENTA_GENERAL.setId("46412");
				// ar.com.zeni.zeniwsdl.ArrayOfCobranzaType
				// _obtenerCobranzas__return2 =
				// port.obtenerCobranzas(AUTH_GENERAL, CUENTA_GENERAL,
				// FECHA_TOPE, _obtenerCobranzas_filtroOperaciones);
				// System.out.println("obtenerCobranzas.result=" +
				// _obtenerCobranzas__return);
				// System.out.println("obtenerCobranzas.result=" +
				// _obtenerCobranzas__return2);
			} catch (FaultType_Exception e) {
				System.out
						.println("Expected exception: FaultType has occurred.");
				System.out.println(e.toString());
			}
		}
		{
			System.out
					.println("Invoking obtenerSeguimientoDeBoletoByContrato...");
			try {
				ar.com.zeni.zeniwsdl.SeguimientoDeBoletoByContratoType _obtenerSeguimientoDeBoletoByContrato__return = port
						.obtenerSeguimientoDeBoletoByContrato(AUTH_GENERAL,
								CONTRATO_ID);
				// System.out.println("obtenerSeguimientoDeBoletoByContrato.result="
				// + _obtenerSeguimientoDeBoletoByContrato__return);
			} catch (FaultType_Exception e) {
				System.out
						.println("Expected exception: FaultType has occurred.");
				System.out.println(e.toString());
			}
		}
		{
			System.out
					.println("Invoking obtenerComentariosFijacionesByContrato...");
			try {
				ArrayOfComentarioFijacionByContratoType _obtenerComentariosFijacionesByContrato__return = port
						.obtenerComentariosFijacionesByContrato(AUTH_GENERAL,
								CONTRATO_ID);
				// System.out.println("obtenerComentariosFijacionesByContrato.result="
				// + _obtenerComentariosFijacionesByContrato__return);
			} catch (FaultType_Exception e) {
				System.out
						.println("Expected exception: FaultType has occurred.");
				System.out.println(e.toString());
			}
		}
		{
			System.out
					.println("Invoking obtenerAjustesComentarioFijacionByContrato...");
			try {
				ArrayOfAjusteComentarioFijacionByContratoType _obtenerAjustesComentarioFijacionByContrato__return = port
						.obtenerAjustesComentarioFijacionByContrato(
								AUTH_GENERAL, CONTRATO_ID);
				// System.out.println("_obtenerAjustesComentarioFijacionByContrato__return.result="
				// + _obtenerAjustesComentarioFijacionByContrato__return);
			} catch (FaultType_Exception e) {
				System.out
						.println("Expected exception: FaultType has occurred.");
				System.out.println(e.toString());
			}
		}
		{
			System.out
					.println("Invoking obtenerComentariosComentarioFijacionByContrato...");
			try {
				ArrayOfComentarioComentarioFijacionByContrato _obtenerComentariosComentarioFijacionByContrato__return = port
						.obtenerComentariosComentarioFijacionByContrato(
								AUTH_GENERAL, CONTRATO_ID);
				// System.out.println("obtenerComentariosComentarioFijacionByContrato.result="
				// + _obtenerComentariosComentarioFijacionByContrato__return);
			} catch (FaultType_Exception e) {
				System.out
						.println("Expected exception: FaultType has occurred.");
				System.out.println(e.toString());
			}
		}
		{
			System.out.println("Invoking obtenerLiquidacionesByContrato...");
			try {
				ar.com.zeni.zeniwsdl.ArrayOfLiquidacionByContratoType _obtenerLiquidacionesByContrato__return = port
						.obtenerLiquidacionesByContrato(AUTH_GENERAL,
								CUENTA_GENERAL.getId(), CONTRATO_ID);
				// ar.com.zeni.zeniwsdl.ArrayOfLiquidacionByContratoType
				// _obtenerLiquidacionesByContrato__return =
				// port.obtenerLiquidacionesByContrato(AUTH_GENERAL, "49801",
				// "3385780");
				// System.out.println("obtenerLiquidacionesByContrato.result=" +
				// _obtenerLiquidacionesByContrato__return);
			} catch (FaultType_Exception e) {
				System.out
						.println("Expected exception: FaultType has occurred.");
				System.out.println(e.toString());
			}
		}
		{
			System.out.println("Invoking obtenerCuposByContrato...");
			try {
				ArrayOfCupoByContratoType _obtenerCupos__return = port
						.obtenerCuposByContrato(AUTH_GENERAL, CONTRATO_ID);
				// System.out.println("obtenerCupos.result=" +
				// _obtenerCupos__return);
			} catch (FaultType_Exception e) {
				System.out
						.println("Expected exception: FaultType has occurred.");
				System.out.println(e.toString());
			}
		}
		{
			System.out.println("Invoking obtenerFijacionesByContrato...");
			try {
				ar.com.zeni.zeniwsdl.ArrayOfFijacionByContratoType _obtenerFijacionesByContrato__return = port
						.obtenerFijacionesByContrato(AUTH_GENERAL, CONTRATO_ID);
				// System.out.println("obtenerFijacionesByContrato.result=" +
				// _obtenerFijacionesByContrato__return);
			} catch (FaultType_Exception e) {
				System.out
						.println("Expected exception: FaultType has occurred.");
				System.out.println(e.toString());
			}
		}
		{
			System.out.println("Invoking obtenerMuestrasByContrato...");
			try {
				ar.com.zeni.zeniwsdl.ArrayOfMuestraByContratoType _obtenerMuestrasByContrato__return = port
						.obtenerMuestrasByContrato(AUTH_GENERAL, CONTRATO_ID);
				// System.out.println("obtenerMuestrasByContrato.result=" +
				// _obtenerMuestrasByContrato__return);
			} catch (FaultType_Exception e) {
				System.out
						.println("Expected exception: FaultType has occurred.");
				System.out.println(e.toString());
			}
		}
		{
			System.out.println("Invoking obtenerAnalisisMuestraByContrato...");
			try {
				AnalisisMuestraByContratoType obtenerAnalisisMuestraByContrato_return = port
						.obtenerAnalisisMuestraByContrato(AUTH_GENERAL,
								"405777" // CONTRATO_ID
								, "960");
				// System.out.println("obtenerAnalisisMuestraByContrato_return.result="
				// + obtenerAnalisisMuestraByContrato_return);
			} catch (FaultType_Exception e) {
				System.out
						.println("Expected exception: FaultType has occurred.");
				System.out.println(e.toString());
			}
		}
		{
			System.out.println("Invoking obtenerEntregasByContrato...");
			try {
				ArrayOfEntregaByContratoType obtenerEntregasByContrato_return = port
						.obtenerEntregasByContrato(AUTH_GENERAL, CONTRATO_ID);
				// System.out.println("obtenerEntregasByContrato_return.result="
				// + obtenerEntregasByContrato_return);
			} catch (FaultType_Exception e) {
				System.out
						.println("Expected exception: FaultType has occurred.");
				System.out.println(e.toString());
			}
		}
		{
			System.out.println("Invoking obtenerCartasDePorteByContrato...");
			try {
				ArrayOfCartaDePorteType obtenerCartasDePorteByContrato_return = port
						.obtenerCartasDePorteByContrato(AUTH_GENERAL,
								CONTRATO_ID);
				// System.out.println("obtenerCartasDePorteByContrato.result=" +
				// obtenerCartasDePorteByContrato_return);
			} catch (FaultType_Exception e) {
				System.out
						.println("Expected exception: FaultType has occurred.");
				System.out.println(e.toString());
			}
		}
		{
			System.out.println("Invoking obtenerEntregasCubiertas...");
			try {
				ArrayOfEntregaCubiertaType obtenerEntregasCubiertas_return = port
						.obtenerEntregasCubiertas(AUTH_GENERAL, CONTRATO_ID,
								ENTREGA_ID);
				// ArrayOfEntregaCubiertaType obtenerEntregasCubiertas_return =
				// port.obtenerEntregasCubiertas(AUTH_GENERAL, "4802903",
				// "7932108");
				// System.out.println("obtenerEntregasCubiertas_return.result="
				// + obtenerEntregasCubiertas_return);
			} catch (FaultType_Exception e) {
				System.out
						.println("Expected exception: FaultType has occurred.");
				e.printStackTrace();
				System.out.println(e.toString());
			}
		}
		{
			System.out.println("Invoking obtenerContratoByContrato...");
			try {
				ContratoType obtenerContratoByContrato__return = port
						.obtenerContratoByContrato(AUTH_GENERAL, CONTRATO_ID,
								CUENTA_GENERAL.getId());
				// System.out.println("obtenerContratoByContrato__return.result="
				// + obtenerContratoByContrato__return);
			} catch (FaultType_Exception e) {
				System.out
						.println("Expected exception: FaultType has occurred.");
				System.out.println(e.toString());
			}
		}
		{
			System.out.println("Invoking obtenerCompradores...");
			try {
				ar.com.zeni.zeniwsdl.ArrayOfCompradorType _obtenerCompradores__return = port
						.obtenerCompradores(AUTH_GENERAL, array_cuentas);
				// System.out.println("obtenerCompradores.result=" +
				// _obtenerCompradores__return);
			} catch (FaultType_Exception e) {
				System.out
						.println("Expected exception: FaultType has occurred.");
				System.out.println(e.toString());
			}
		}
		// {
		// System.out.println("Invoking obtenerInformacionCuentaCorriente...");
		// ar.com.zeni.zeniwsdl.EnumDeMovimientoType
		// _obtenerInformacionCuentaCorriente_filtroDeMovimiento =
		// ar.com.zeni.zeniwsdl.EnumDeMovimientoType.MOVIMIENTO;
		// try {
		// // CUENTA_GENERAL.setId("47238");
		// FILTRO_DE_MONEDA.setId("1717");
		// ar.com.zeni.zeniwsdl.InformacionCuentaCorrienteType
		// _obtenerInformacionCuentaCorriente__return =
		// port.obtenerInformacionCuentaCorriente(AUTH_GENERAL, CUENTA_GENERAL,
		// RANGO_DEFECHAS, FILTRO_DE_MONEDA,
		// _obtenerInformacionCuentaCorriente_filtroDeMovimiento, "34", "23");
		// // System.out.println("obtenerInformacionCuentaCorriente.result=" +
		// _obtenerInformacionCuentaCorriente__return);
		// // _obtenerInformacionCuentaCorriente__return =
		// port.obtenerInformacionCuentaCorriente(AUTH_GENERAL, CUENTA_GENERAL,
		// RANGO_DEFECHAS, FILTRO_DE_MONEDA,
		// _obtenerInformacionCuentaCorriente_filtroDeMovimiento, null, null);
		// // System.out.println("obtenerInformacionCuentaCorriente.result=" +
		// _obtenerInformacionCuentaCorriente__return);
		// } catch (FaultType_Exception e) {
		// System.out.println("Expected exception: FaultType has occurred.");
		// System.out.println(e.toString());
		// }
		// }
		{
			System.out.println("Invoking obtenerComprobantes...");
			try {
				ar.com.zeni.zeniwsdl.ArrayOfComprobanteType _obtenerComprobantes__return = port
						.obtenerComprobantes(AUTH_GENERAL, CUENTA_GENERAL,
								TIPO_CONSULTA_COMP, RANGO_DEFECHAS,
								TIPO_COMPRODORVONDODOR, COTRAPARTE_ID,
								TIPODECOMPROBANTE, DESCARGADO);
				// _obtenerComprobantes__return =
				// port.obtenerComprobantes(AUTH_GENERAL, CUENTA_GENERAL,
				// TIPO_CONSULTA_COMP, RANGO_DEFECHAS, TIPO_COMPRODORVONDODOR,
				// COTRAPARTE_ID, TIPODECOMPROBANTE, SINOType.SI);
				// _obtenerComprobantes__return =
				// port.obtenerComprobantes(AUTH_GENERAL, CUENTA_GENERAL,
				// TIPO_CONSULTA_COMP, RANGO_DEFECHAS, TIPO_COMPRODORVONDODOR,
				// COTRAPARTE_ID, TIPODECOMPROBANTE, SINOType.NO);
				// _obtenerComprobantes__return =
				// port.obtenerComprobantes(AUTH_GENERAL, CUENTA_GENERAL,
				// TIPO_CONSULTA_COMP, RANGO_DEFECHAS, TIPO_COMPRODORVONDODOR,
				// COTRAPARTE_ID, TIPODECOMPROBANTE, SINOType.DEFAULT);
				// _obtenerComprobantes__return =
				// port.obtenerComprobantes(AUTH_GENERAL, CUENTA_GENERAL,
				// TIPO_CONSULTA_COMP, RANGO_DEFECHAS, TIPO_COMPRODORVONDODOR,
				// COTRAPARTE_ID, TIPODECOMPROBANTE, SINOType.INDISTINTO);
				// _obtenerComprobantes__return =
				// port.obtenerComprobantes(AUTH_GENERAL, CUENTA_GENERAL,
				// EnumTipoConsultaComprobanteType.DIA, RANGO_DEFECHAS,
				// TIPO_COMPRODORVONDODOR, COTRAPARTE_ID, TIPODECOMPROBANTE,
				// SINOType.SI);
				// _obtenerComprobantes__return =
				// port.obtenerComprobantes(AUTH_GENERAL, CUENTA_GENERAL,
				// EnumTipoConsultaComprobanteType.MES, RANGO_DEFECHAS,
				// TIPO_COMPRODORVONDODOR, COTRAPARTE_ID, TIPODECOMPROBANTE,
				// SINOType.NO);
				// System.out.println("obtenerComprobantes.result=" +
				// _obtenerComprobantes__return);

			} catch (FaultType_Exception e) {
				System.out
						.println("Expected exception: FaultType has occurred.");
				System.out.println(e.toString());
			}
		}
		{
			System.out.println("Invoking obtenerMermasByEntrega...");
			try {
				ArrayOfMermasByEntregaType _obtenerMermasByEntrega__return = port
						.obtenerMermasByEntrega(AUTH_GENERAL, ENTREGA_ID);
				// System.out.println("obtenerMermasByEntrega.result=" +
				// _obtenerMermasByEntrega__return);
			} catch (FaultType_Exception e) {
				System.out
						.println("Expected exception: FaultType has occurred.");
				System.out.println(e.toString());
			}
		}
		{
			System.out.println("Invoking obtenerListadoDeEntregas...");
			ar.com.zeni.zeniwsdl.EnumCompradorVendedorType _obtenerListadoDeEntregas_condicion = ar.com.zeni.zeniwsdl.EnumCompradorVendedorType.AMBOS;
			try {
				ar.com.zeni.zeniwsdl.ArrayOfEntregaType _obtenerListadoDeEntregas__return = port
						.obtenerListadoDeEntregas(AUTH_GENERAL, CUENTA_GENERAL,
								RANGO_DEFECHAS,
								_obtenerListadoDeEntregas_condicion,
								PRODUCTOS_GENERAL);
				// System.out.println("obtenerListadoDeEntregas.result=" +
				// _obtenerListadoDeEntregas__return);
			} catch (FaultType_Exception e) {
				System.out
						.println("Expected exception: FaultType has occurred.");
				System.out.println(e.toString());
			}
		}
		// {
		// System.out.println("Invoking obtenerEstadoDeContratos...");
		// ar.com.zeni.zeniwsdl.FechaTimeType
		// _obtenerEstadoDeContratos_fechaTope = new
		// ar.com.zeni.zeniwsdl.FechaTimeType();
		// _obtenerEstadoDeContratos_fechaTope.setFecha(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2012-09-10T15:58:27.083-03:00"));
		// try {
		// //ar.com.zeni.zeniwsdl.ArrayOfEstadosDeContratoType
		// _obtenerEstadoDeContratos__return =
		// port.obtenerEstadoDeContratos(AUTH_GENERAL, CUENTA_GENERAL,
		// FECHA_TOPE, EnumCompradorVendedorType.COMPRADOR, ACTIVIDAD_ID);
		// // System.out.println("obtenerEstadoDeContratos.result=" +
		// _obtenerEstadoDeContratos__return);
		// } catch (FaultType_Exception e) {
		// System.out.println("Expected exception: FaultType has occurred.");
		// System.out.println(e.toString());
		// }
		// }
		{
			System.out.println("Invoking obtenerCartasDePorte...");
			try {
				ar.com.zeni.zeniwsdl.ArrayOfCartaDePorteType _obtenerCartasDePorte__return = port
						.obtenerCartasDePorte(AUTH_GENERAL, CUENTA_GENERAL,
								RANGO_DEFECHAS, PRODUCTOS_GENERAL);
				// System.out.println("obtenerCartasDePorte.result=" +
				// _obtenerCartasDePorte__return);
			} catch (FaultType_Exception e) {
				System.out
						.println("Expected exception: FaultType has occurred.");
				System.out.println(e.toString());
			}
		}
		{
			System.out.println("Invoking obtenerCalidades...");
			try {
				ar.com.zeni.zeniwsdl.ArrayOfCalidadType _obtenerCalidades__return = port
						.obtenerCalidades(AUTH_GENERAL, array_cuentas);
				// System.out.println("obtenerCalidades.result=" +
				// _obtenerCalidades__return);
			} catch (FaultType_Exception e) {
				System.out
						.println("Expected exception: FaultType has occurred.");
				System.out.println(e.toString());
			}
		}
		{
			System.out.println("Invoking obtenerCampanias...");
			try {
				ar.com.zeni.zeniwsdl.ArrayOfCampaniaType _obtenerCampanias__return = port
						.obtenerCampanias(AUTH_GENERAL, array_cuentas);
				// System.out.println("obtenerCampanias.result=" +
				// _obtenerCampanias__return);
			} catch (FaultType_Exception e) {
				System.out
						.println("Expected exception: FaultType has occurred.");
				System.out.println(e.toString());
			}
		}
		{
			System.out.println("Invoking obtenerCondicionesDePago...");
			try {
				ar.com.zeni.zeniwsdl.ArrayOfCondicionDePagoType _obtenerCondicionesDePago__return = port
						.obtenerCondicionesDePago(AUTH_GENERAL);
				// System.out.println("obtenerCondicionesDePago.result=" +
				// _obtenerCondicionesDePago__return);
			} catch (FaultType_Exception e) {
				System.out
						.println("Expected exception: FaultType has occurred.");
				System.out.println(e.toString());
			}
		}
		{
			System.out.println("Invoking obtenerContratos...");
			java.lang.String _obtenerContratos_nroZeni = ZeniContextServer.VACIO;
			java.lang.String _obtenerContratos_nroContratoComprador = ZeniContextServer.VACIO;
			java.lang.String _obtenerContratos_nroContratoVendedor = ZeniContextServer.VACIO;
			ar.com.zeni.zeniwsdl.EnumIncluirType _obtenerContratos_incluir = ar.com.zeni.zeniwsdl.EnumIncluirType.SL_FINAL;
			java.lang.String _obtenerContratos_precio = ZeniContextServer.VACIO;
			ar.com.zeni.zeniwsdl.EnumOrdenamientoContratosType _obtenerContratos_ordenamiento = ar.com.zeni.zeniwsdl.EnumOrdenamientoContratosType.NUMERO;
			java.lang.String _obtenerContratos_vendedorId = ZeniContextServer.VACIO;
			java.lang.String _obtenerContratos_compradorId = ZeniContextServer.VACIO;
			java.lang.String _obtenerContratos_calidadId = ZeniContextServer.VACIO;
			java.lang.String _obtenerContratos_operatoriaId = ZeniContextServer.VACIO;
			java.lang.String _obtenerContratos_campaniaId = ZeniContextServer.VACIO;
			java.lang.String _obtenerContratos_condDePagoId = ZeniContextServer.VACIO;
			String _obtenerContratos_cartaDePorte = ZeniContextServer.VACIO;
                        ar.com.zeni.zeniwsdl.ArrayOfContratoType _obtenerContratos__retur2 = port
                                .obtenerContratos(AUTH_GENERAL, array_cuentas,
                                        _obtenerContratos_nroZeni,
                                        _obtenerContratos_nroContratoComprador,
                                        _obtenerContratos_nroContratoVendedor,
                                        _obtenerContratos_incluir,
                                        _obtenerContratos_precio,
                                        _obtenerContratos_ordenamiento, null,
                                        PRODUCTOS_GENERAL,
                                        _obtenerContratos_vendedorId,
                                        _obtenerContratos_compradorId,
                                        _obtenerContratos_calidadId,
                                        _obtenerContratos_operatoriaId,
                                        _obtenerContratos_campaniaId,
                                        _obtenerContratos_condDePagoId,
                                        EnumCompradorVendedorType.AMBOS,
                                        _obtenerContratos_cartaDePorte,null);
                        // System.out.println("obtenerContratos.result=" +
                        // _obtenerContratos__retur2);
		}
		{
			System.out.println("Invoking obtenerOperatoriasCobroMercaderia...");
			try {
				ar.com.zeni.zeniwsdl.ArrayOfOperatoriasCobroMercaderiaType _obtenerOperatoriasCobroMercaderia__return = port
						.obtenerOperatoriasCobroMercaderia(AUTH_GENERAL,
								CLIENTE_GENERAL.getId());
				// System.out.println("obtenerOperatoriasCobroMercaderia.result="
				// + _obtenerOperatoriasCobroMercaderia__return);
			} catch (FaultType_Exception e) {
				System.out
						.println("Expected exception: FaultType has occurred.");
				System.out.println(e.toString());
			}
		}
		{
			System.out.println("Invoking obtenerListadoDeOperatoria...");
			EnumOpcionesListadoEntrega _obtenerListadoDeOperatoria_opciones = EnumOpcionesListadoEntrega.CONTRATO_A_FIJAR;
			java.lang.String _obtenerListadoDeOperatoria_campaniaId = ZeniContextServer.VACIO;
			try {
				ar.com.zeni.zeniwsdl.ArrayOfOperatoriaDListadoType _obtenerListadoDeOperatoria__return = port
						.obtenerListadoDeOperatoria(AUTH_GENERAL,
								CUENTA_GENERAL, RANGO_DEFECHAS,
								_obtenerListadoDeOperatoria_opciones,
								_obtenerListadoDeOperatoria_campaniaId,
								PRODUCTOS_GENERAL);
				// System.out.println("obtenerListadoDeOperatoria.result=" +
				// _obtenerListadoDeOperatoria__return);
			} catch (FaultType_Exception e) {
				System.out
						.println("Expected exception: FaultType has occurred.");
				System.out.println(e.toString());
			}
		}
		{
			System.out.println("Invoking obtenerDatosDeCuenta...");
			try {
				ar.com.zeni.zeniwsdl.CuentaDatosType _obtenerDatosDeCuenta__return = port
						.obtenerDatosDeCuenta(AUTH_GENERAL, CUENTA_GENERAL);
				// System.out.println("obtenerDatosDeCuenta.result=" +
				// _obtenerDatosDeCuenta__return);
			} catch (FaultType_Exception e) {
				System.out
						.println("Expected exception: FaultType has occurred.");
				System.out.println(e.toString());
			}
		}
		// {
		// System.out.println("Invoking newOperation...");
		// java.lang.String _newOperation_in = "_newOperation_in1155507307";
		// try {
		// ar.com.zeni.zeniwsdl.FileType _newOperation__return =
		// port.newOperation(_newOperation_in);
		// System.out.println("newOperation.result=" + _newOperation__return);
		//
		// } catch (FaultType_Exception e) {
		// System.out.println("Expected exception: FaultType has occurred.");
		// System.out.println(e.toString());
		// }
		// }
		{
			System.out.println("Invoking obtenerOperatorias...");
			try {
				ar.com.zeni.zeniwsdl.ArrayOfOperatoriaType _obtenerOperatorias__return = port
						.obtenerOperatorias(AUTH_GENERAL, array_cuentas);
				// System.out.println("obtenerOperatorias.result=" +
				// _obtenerOperatorias__return);
			} catch (FaultType_Exception e) {
				System.out
						.println("Expected exception: FaultType has occurred.");
				System.out.println(e.toString());
			}
		}
		{
			System.out.println("Invoking obtenerProducto...");
			try {
				ar.com.zeni.zeniwsdl.ProductoType _obtenerProducto__return = port
						.obtenerProducto(AUTH_GENERAL, PRODUCTO_ID);
				// System.out.println("obtenerProducto.result=" +
				// _obtenerProducto__return);
			} catch (FaultType_Exception e) {
				System.out
						.println("Expected exception: FaultType has occurred.");
				System.out.println(e.toString());
			}
		}
		{
			System.out.println("Invoking obtenerActividades...");
			try {
				ar.com.zeni.zeniwsdl.ArrayOfActividadesType _obtenerActividades__return = port
						.obtenerActividades(AUTH_GENERAL,
								CLIENTE_GENERAL.getId());
				// System.out.println("obtenerActividades.result=" +
				// _obtenerActividades__return);
			} catch (FaultType_Exception e) {
				System.out
						.println("Expected exception: FaultType has occurred.");
				System.out.println(e.toString());
			}
		}
		{
			System.out.println("Invoking obtenerMoneda...");
			try {
				ar.com.zeni.zeniwsdl.MonedaType _obtenerMoneda__return = port
						.obtenerMoneda(AUTH_GENERAL, FILTRO_DE_MONEDA.getId());
				// System.out.println("obtenerMoneda.result=" +
				// _obtenerMoneda__return);
			} catch (FaultType_Exception e) {
				System.out
						.println("Expected exception: FaultType has occurred.");
				System.out.println(e.toString());
			}
		}
		{
			System.out.println("Invoking obtenerResumenDeCuentaCorriente...");
			try {
				ar.com.zeni.zeniwsdl.ResumenCuentaCorrienteType _obtenerResumenDeCuentaCorriente__return = port
						.obtenerResumenDeCuentaCorriente(AUTH_GENERAL,
								CUENTA_GENERAL);
				// System.out.println("obtenerResumenDeCuentaCorriente.result="
				// + _obtenerResumenDeCuentaCorriente__return);
			} catch (FaultType_Exception e) {
				System.out
						.println("Expected exception: FaultType has occurred.");
				System.out.println(e.toString());
			}
		}
		{
			System.out.println("Invoking obtenerMonedas...");
			try {
				ar.com.zeni.zeniwsdl.ArrayOfMonedaType _obtenerMonedas__return = port
						.obtenerMonedas(AUTH_GENERAL);
				// System.out.println("obtenerMonedas.result=" +
				// _obtenerMonedas__return);
			} catch (FaultType_Exception e) {
				System.out
						.println("Expected exception: FaultType has occurred.");
				System.out.println(e.toString());
			}
		}
		{
			System.out.println("Invoking obtenerMuestras...");
			try {
				// CUENTA_GENERAL.setId("21374");
				// ArrayOfMuestraType obtenerMuestras_return =
				// port.obtenerMuestras(AUTH_GENERAL, CUENTA_GENERAL,
				// RANGO_DEFECHAS, CONTRATO_ID, CAMPANIA_ID, PRODUCTOS_GENERAL);
				ArrayOfMuestraType obtenerMuestras_return = port
						.obtenerMuestras(AUTH_GENERAL, CUENTA_GENERAL,
								RANGO_DEFECHAS, "", "", PRODUCTOS_GENERAL);
				// System.out.println("obtenerMuestras_return.result=" +
				// obtenerMuestras_return);
			} catch (FaultType_Exception e) {
				System.out
						.println("Expected exception: FaultType has occurred.");
				System.out.println(e.toString());
			}
		}
		{
			System.out.println("Invoking obtenerSaldoDeCliente...");
			try {
				ar.com.zeni.zeniwsdl.ArrayOfSaldoDeClienteType _obtenerSaldoDeCliente__return = port
						.obtenerSaldoDeCliente(AUTH_GENERAL,
								CLIENTE_GENERAL.getId());
				// System.out.println("obtenerSaldoDeCliente.result=" +
				// _obtenerSaldoDeCliente__return);
			} catch (FaultType_Exception e) {
				System.out
						.println("Expected exception: FaultType has occurred.");
				System.out.println(e.toString());
			}
		}
		{
			System.out.println("Invoking obtenerVendedores...");
			try {
				ar.com.zeni.zeniwsdl.ArrayOfVendedorType _obtenerVendedores__return = port
						.obtenerVendedores(AUTH_GENERAL, array_cuentas);
				// System.out.println("obtenerVendedores.result=" +
				// _obtenerVendedores__return);
			} catch (FaultType_Exception e) {
				System.out
						.println("Expected exception: FaultType has occurred.");
				System.out.println(e.toString());
			}
		}
		{
			System.out.println("Invoking obtenerFechaDeSincronizacion...");
			ar.com.zeni.zeniwsdl.FechaTimeType _obtenerFechaDeSincronizacion_fechaEnPc = new ar.com.zeni.zeniwsdl.FechaTimeType();
			_obtenerFechaDeSincronizacion_fechaEnPc
					.setFecha(javax.xml.datatype.DatatypeFactory.newInstance()
							.newXMLGregorianCalendar(
									"2012-09-10T15:58:27.193-03:00"));
			try {
				ar.com.zeni.zeniwsdl.FechaDiferenciaType _obtenerFechaDeSincronizacion__return = port
						.obtenerFechaDeSincronizacion(_obtenerFechaDeSincronizacion_fechaEnPc);
				// System.out.println("obtenerFechaDeSincronizacion.result=" +
				// _obtenerFechaDeSincronizacion__return);
			} catch (FaultType_Exception e) {
				System.out
						.println("Expected exception: FaultType has occurred.");
				System.out.println(e.toString());
			}
		}
		{
			System.out.println("Invoking obtenerContrapartesByCuenta...");
			try {
				ar.com.zeni.zeniwsdl.ArrayOfContraparteType _obtenerContrapartesByCuenta__return = port
						.obtenerContrapartesByCuenta(AUTH_GENERAL,
								CUENTA_GENERAL);
				// System.out.println("obtenerContrapartesByCuenta.result=" +
				// _obtenerContrapartesByCuenta__return);
			} catch (FaultType_Exception e) {
				System.out
						.println("Expected exception: FaultType has occurred.");
				System.out.println(e.toString());
			}
		}
		// {
		// System.out.println("invoking descargarcomprobante...");
		// try {
		// ar.com.zeni.zeniwsdl.FileType _descargarcomprobante__return =
		// port.descargarComprobante(AUTH_GENERAL, CUENTA_GENERAL.getId(),
		// COMPROBANTE_ID, COMPROBANTE_TIPO);
		// ar.com.zeni.zeniwsdl.FileType _descargarcomprobante__return =
		// port.descargarComprobante(AUTH_GENERAL, CUENTA_GENERAL.getId(),
		// "14892905", "FA", SINOType.SI);
		// System.out.println("descargarcomprobante.result=" +
		// _descargarcomprobante__return);
		// FileOutputStream fos = new FileOutputStream("/tmp/" +
		// _descargarcomprobante__return.getNombreConExtension());
		// fos.write(_descargarcomprobante__return.getData());
		// fos.flush();
		// } catch (Exception e) {
		// System.out.println("expected exception: faulttype has occurred.");
		// System.out.println(e.toString());
		// }
		// }
		{
			System.out.println("Invoking marcarComprobanteDescargado...");
			try {
				java.lang.String _marcarComprobanteDescargado__return = port
						.marcarComprobanteDescargado(AUTH_GENERAL,
								COMPROBANTE_ID, SINOType.SI);
				// System.out.println("marcarComprobanteDescargado.result=" +
				// _marcarComprobanteDescargado__return);
			} catch (FaultType_Exception e) {
				System.out
						.println("Expected exception: FaultType has occurred.");
				System.out.println(e.toString());
			}
		}
		{
			System.out.println("Invoking obtenerCupos...");
			try {
				ar.com.zeni.zeniwsdl.CuposResponseType _obtenerCupos__return = port
						.obtenerCupos(AUTH_GENERAL, RANGO_DEFECHAS,
								CLIENTE_GENERAL.getId(),"");// CONTRATO_ID);
				// System.out.println("obtenerCupos.result=" +
				// _obtenerCupos__return);
			} catch (FaultType_Exception e) {
				System.out
						.println("Expected exception: FaultType has occurred.");
				System.out.println(e.toString());
			}
		}
		{
			System.out.println("Invoking obtenerNoticias...");
			java.lang.String _obtenerNoticias_newId = "_obtenerNoticias_newId1170231598";
			try {
				ar.com.zeni.zeniwsdl.ArrayOfNewsType _obtenerNoticias__return = port
						.obtenerNoticias(AUTH_GENERAL, "");
				// System.out.println("obtenerNoticias.result=" +
				// _obtenerNoticias__return);
			} catch (FaultType_Exception e) {
				System.out
						.println("Expected exception: FaultType has occurred.");
				System.out.println(e.toString());
			}
		}
		{
			System.out
					.println("Invoking obtenerSituacionImpositivaRegistroFiscal...");
			try {
				ar.com.zeni.zeniwsdl.SituacionImpositivaRegistroFiscalType _obtenerSituacionImpositivaRegistroFiscal__return = port
						.obtenerSituacionImpositivaRegistroFiscal(AUTH_GENERAL,
								CUENTA_GENERAL.getId());
				// System.out.println("obtenerSituacionImpositivaRegistroFiscal.result="
				// + _obtenerSituacionImpositivaRegistroFiscal__return);
			} catch (FaultType_Exception e) {
				System.out
						.println("Expected exception: FaultType has occurred.");
				System.out.println(e.toString());
			}
		}
		{
			System.out
					.println("Invoking obtenerSituacionImpositivaInformacionImpositiva...");
			try {
				ar.com.zeni.zeniwsdl.ArrayOfExtensionesPerIVAType _obtenerSituacionImpositivaInformacionImpositiva__return = port
						.obtenerSituacionImpositivaInformacionImpositiva(
								AUTH_GENERAL, CUENTA_GENERAL.getId());
				// System.out.println("obtenerSituacionImpositivaInformacionImpositiva.result="
				// + _obtenerSituacionImpositivaInformacionImpositiva__return);
			} catch (FaultType_Exception e) {
				System.out
						.println("Expected exception: FaultType has occurred.");
				System.out.println(e.toString());
			}
		}
		{
			System.out
					.println("Invoking obtenerSituacionImpositivaGanancias...");
			try {
				ar.com.zeni.zeniwsdl.SituacionImpositivaGananciasType _obtenerSituacionImpositivaGanancias__return = port
						.obtenerSituacionImpositivaGanancias(AUTH_GENERAL,
								CUENTA_GENERAL.getId());
				// System.out.println("obtenerSituacionImpositivaGanancias.result="
				// + _obtenerSituacionImpositivaGanancias__return);
			} catch (FaultType_Exception e) {
				System.out
						.println("Expected exception: FaultType has occurred.");
				System.out.println(e.toString());
			}
		}
		{
			System.out
					.println("Invoking obtenerSituacionImpositivaCabecera...");
			try {
				ar.com.zeni.zeniwsdl.SituacionImpositivaCabeceraType _obtenerSituacionImpositivaCabecera__return = port
						.obtenerSituacionImpositivaCabecera(AUTH_GENERAL,
								CUENTA_GENERAL.getId());
				// System.out.println("obtenerSituacionImpositivaCabecera.result="
				// + _obtenerSituacionImpositivaCabecera__return);
			} catch (FaultType_Exception e) {
				System.out
						.println("Expected exception: FaultType has occurred.");
				System.out.println(e.toString());
			}
		}
		{
			System.out
					.println("Invoking obtenerSituacionImpositivaIngBrutos...");
			try {
				ar.com.zeni.zeniwsdl.SituacionImpositivaIngBrutosType _obtenerSituacionImpositivaIngBrutos__return = port
						.obtenerSituacionImpositivaIngBrutos(AUTH_GENERAL,
								CUENTA_GENERAL.getId());
				// System.out.println("obtenerSituacionImpositivaIngBrutos.result="
				// + _obtenerSituacionImpositivaIngBrutos__return);
			} catch (FaultType_Exception e) {
				System.out
						.println("Expected exception: FaultType has occurred.");
				System.out.println(e.toString());
			}
		}
		// {
		// System.out.println("Invoking obtenerPDFaMostrarPantallas...");
		// java.lang.String _obtenerPDFaMostrarPantallas_categoryId =
		// "_obtenerPDFaMostrarPantallas_categoryId455315648";
		// try {
		// ArrayOfFilesType _obtenerPDFaMostrarPantallas__return =
		// port.obtenerPDFaMostrarPantallas(AUTH_GENERAL, "CM");
		// System.out.println("obtenerPDFaMostrarPantallas.result=" +
		// _obtenerPDFaMostrarPantallas__return);
		// _obtenerPDFaMostrarPantallas__return =
		// port.obtenerPDFaMostrarPantallas(AUTH_GENERAL, "RC");
		// System.out.println("obtenerPDFaMostrarPantallas.result=" +
		// _obtenerPDFaMostrarPantallas__return);
		// _obtenerPDFaMostrarPantallas__return =
		// port.obtenerPDFaMostrarPantallas(AUTH_GENERAL, "PI");
		// System.out.println("obtenerPDFaMostrarPantallas.result=" +
		// _obtenerPDFaMostrarPantallas__return);
		// _obtenerPDFaMostrarPantallas__return =
		// port.obtenerPDFaMostrarPantallas(AUTH_GENERAL, "RS");
		// System.out.println("obtenerPDFaMostrarPantallas.result=" +
		// _obtenerPDFaMostrarPantallas__return);
		// _obtenerPDFaMostrarPantallas__return =
		// port.obtenerPDFaMostrarPantallas(AUTH_GENERAL, "CC");
		// System.out.println("obtenerPDFaMostrarPantallas.result=" +
		// _obtenerPDFaMostrarPantallas__return);
		// _obtenerPDFaMostrarPantallas__return =
		// port.obtenerPDFaMostrarPantallas(AUTH_GENERAL, "SF");
		// System.out.println("obtenerPDFaMostrarPantallas.result=" +
		// _obtenerPDFaMostrarPantallas__return);
		// _obtenerPDFaMostrarPantallas__return =
		// port.obtenerPDFaMostrarPantallas(AUTH_GENERAL, "NC");
		// System.out.println("obtenerPDFaMostrarPantallas.result=" +
		// _obtenerPDFaMostrarPantallas__return);
		// _obtenerPDFaMostrarPantallas__return =
		// port.obtenerPDFaMostrarPantallas(AUTH_GENERAL, "MP");
		// System.out.println("obtenerPDFaMostrarPantallas.result=" +
		// _obtenerPDFaMostrarPantallas__return);
		// _obtenerPDFaMostrarPantallas__return =
		// port.obtenerPDFaMostrarPantallas(AUTH_GENERAL, "BI");
		// System.out.println("obtenerPDFaMostrarPantallas.result=" +
		// _obtenerPDFaMostrarPantallas__return);
		// _obtenerPDFaMostrarPantallas__return =
		// port.obtenerPDFaMostrarPantallas(AUTH_GENERAL, "NI");
		// System.out.println("obtenerPDFaMostrarPantallas.result=" +
		// _obtenerPDFaMostrarPantallas__return);
		// _obtenerPDFaMostrarPantallas__return =
		// port.obtenerPDFaMostrarPantallas(AUTH_GENERAL, "CL");
		// System.out.println("obtenerPDFaMostrarPantallas.result=" +
		// _obtenerPDFaMostrarPantallas__return);
		// ArrayOfNormCromType catre =
		// port.obtenerNormasDeComercializacion(AUTH_GENERAL, "");
		// System.out.println("obtenerPDFaMostrarPantallas.resultd=" + catre);
		// } catch (FaultType_Exception e) {
		// System.out.println("Expected exception: FaultType has occurred.");
		// System.out.println(e.toString());
		// }
		// }
		// {
		// System.out.println("Invoking descargarPDFaMostrarPantallas...");
		// try {
		// FileType descargarPDFaMos =
		// port.descargarPDFaMostrarPantallas(AUTH_GENERAL,
		// "00013536870261120000", "NC");
		// FileOutputStream fos = new FileOutputStream("/tmp/" +
		// descargarPDFaMos.getNombreConExtension());
		// System.out.println(descargarPDFaMos.getTamanio());
		// fos.write(descargarPDFaMos.getData());
		// fos.flush();
		// fos.close();
		// } catch (FaultType_Exception e) {
		// System.out.println("Expected exception: FaultType has occurred.");
		// e.printStackTrace();
		// } catch (IOException e) {
		// e.printStackTrace();
		// }
		// }
		{
			System.out.println("Invoking obtenerNormasDeComercializacion...");
			try {
				ArrayOfNormCromType arrayOfNormCromType = port
						.obtenerNormasDeComercializacion(AUTH_GENERAL,
								"00013536870261120000");
				// System.out.println(arrayOfNormCromType);
			} catch (FaultType_Exception e) {
				System.out
						.println("Expected exception: FaultType has occurred.");
				e.printStackTrace();
			}
		}
		{
			System.out.println("Invoking obtenerMercados...");
			try {
				ArrayOfMercadoType merc = port.obtenerMercados(AUTH_GENERAL);
				// System.out.println(merc);
			} catch (FaultType_Exception e) {
				System.out
						.println("Expected exception: FaultType has occurred.");
				e.printStackTrace();
			}
		}
		{
			System.out.println("Invoking obtenerProductosMAT...");
			try {
				ArrayOfProductoMATType prods = port
						.obtenerProductosMAT(AUTH_GENERAL);
				System.out.println(prods);
			} catch (FaultType_Exception e) {
				System.out
						.println("Expected exception: FaultType has occurred.");
				e.printStackTrace();
			}
		}
		{
			System.out.println("Invoking obtenerDestinosMAT...");
			try {
				ArrayOfDestinoMATType dest = port
						.obtenerDestinosMAT(AUTH_GENERAL);
				// System.out.println(dest);
			} catch (FaultType_Exception e) {
				System.out
						.println("Expected exception: FaultType has occurred.");
				e.printStackTrace();
			}
		}
		{
			System.out.println("Invoking obtenerOperacionesMAT...");
			try {
				ArrayOfMercadoType merc = port.obtenerMercados(AUTH_GENERAL);
				ArrayOfProductoMATType prods = port
						.obtenerProductosMAT(AUTH_GENERAL);
				ArrayOfDestinoMATType dest = port
						.obtenerDestinosMAT(AUTH_GENERAL);
				ArrayOfOperacionMATType opera = port.obtenerOperacionesMAT(
						AUTH_GENERAL, CUENTA_GENERAL,
						EnumCompraVentaType.AMBOS, EnumEstadoType.TODOS,
						EnumSucursalType.BUENOS_AIRES, merc, RANGO_DEFECHAS,
						EnumTipoOperacionMatType.AMBOS, prods, dest, "320.32",
						null, null, EnumTipoOperacionType.ESTADISTICO);
				// opera = port.obtenerOperacionesMAT(AUTH_GENERAL,
				// CUENTA_GENERAL, EnumCompraVentaType.AMBOS,
				// EnumEstadoType.TODOS, EnumSucursalType.BUENOS_AIRES, merc,
				// RANGO_DEFECHAS, EnumTipoOperacionMatType.AMBOS, prods, dest,
				// null, null, null);
				opera = port.obtenerOperacionesMAT(AUTH_GENERAL,
						CUENTA_GENERAL, EnumCompraVentaType.AMBOS,
						EnumEstadoType.TODOS, EnumSucursalType.BUENOS_AIRES,
						merc, RANGO_DEFECHAS, EnumTipoOperacionMatType.AMBOS,
						prods, dest, "320.32", null, null,
						EnumTipoOperacionType.ABIERTAS);
				// System.out.println(opera);
			} catch (FaultType_Exception e) {
				System.out
						.println("Expected exception: FaultType has occurred.");
				e.printStackTrace();
			}
		}
		{
			System.out.println("Invoking obtenerResumenMAT...");
			try {
				ArrayOfMercadoType merc = port.obtenerMercados(AUTH_GENERAL);
				ArrayOfProductoMATType prods = port
						.obtenerProductosMAT(AUTH_GENERAL);
				ArrayOfDestinoMATType dest = port
						.obtenerDestinosMAT(AUTH_GENERAL);
				ArrayOfResumenMATType opera = port.obtenerResumenMAT(
						AUTH_GENERAL, CUENTA_GENERAL,
						EnumCompraVentaType.AMBOS, EnumEstadoType.TODOS,
						EnumSucursalType.BUENOS_AIRES, merc, RANGO_DEFECHAS,
						EnumTipoOperacionMatType.AMBOS, prods, dest, null);
				// opera = port.obtenerResumenMAT(AUTH_GENERAL, CUENTA_GENERAL,
				// EnumCompraVentaType.AMBOS, EnumEstadoType.TODOS,
				// EnumSucursalType.BUENOS_AIRES, merc, RANGO_DEFECHAS,
				// EnumTipoOperacionMatType.AMBOS, prods, dest, null);
				// System.out.println(opera);
			} catch (FaultType_Exception e) {
				System.out
						.println("Expected exception: FaultType has occurred.");
				e.printStackTrace();
			}
		}
		{
			System.out.println("Invoking obtenerCuentaCorrienteContable...");
			try {
				ObtenerCuentaCorrienteContableType _obtenerCuentaCorrienteContable__return = port
						.obtenerCuentaCorrienteContable(AUTH_GENERAL,
								CUENTA_GENERAL, RANGO_DEFECHAS,
								FILTRO_DE_MONEDA);
				// CUENTA_GENERAL.setId("4318");
				// ObtenerCuentaCorrienteContableType
				// _obtenerCuentaCorrienteContable__return =
				// port.obtenerCuentaCorrienteContable(AUTH_GENERAL,
				// CUENTA_GENERAL, RANGO_DEFECHAS, null);
				// System.out.println("obtenerCuentaCorrienteContable.result=" +
				// _obtenerCuentaCorrienteContable__return);
				// CUENTA_GENERAL.setId("1272");
				// _obtenerCuentaCorrienteContable__return =
				// port.obtenerCuentaCorrienteContable(AUTH_GENERAL,
				// CUENTA_GENERAL, RANGO_DEFECHAS, null);
				// System.out.println("obtenerCuentaCorrienteContable.result=" +
				// _obtenerCuentaCorrienteContable__return);
			} catch (FaultType_Exception e) {
				System.out
						.println("Expected exception: FaultType has occurred.");
				System.out.println(e.toString());
			}
		}
		// {
		// System.out.println("Invoking descargarPDFaMostrarPantallas...");
		// try {
		// FileType descargarPDFaMos =
		// port.descargarPDFaMostrarPantallas(AUTH_GENERAL,
		// "00013542183140300001", "NC");
		// FileOutputStream fos = new FileOutputStream("/tmp/" +
		// descargarPDFaMos.getNombreConExtension());
		// System.out.println(descargarPDFaMos.getTamanio());
		// fos.write(descargarPDFaMos.getData());
		// fos.flush();
		// fos.close();
		// } catch (FaultType_Exception e) {
		// System.out.println("Expected exception: FaultType has occurred.");
		// e.printStackTrace();
		// } catch (IOException e) {
		// e.printStackTrace();
		// }
		// }
	}
}