
package ar.com.zeni.zeniwsdl;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.6.1
 * 2015-01-13T18:15:05.820-03:00
 * Generated source version: 2.6.1
 */

@WebFault(name = "FaultType", targetNamespace = "http://www.zeni.com.ar/ZeniWSDL/")
public class FaultType_Exception extends Exception {
    
    private ar.com.zeni.zeniwsdl.FaultType faultType;

    public FaultType_Exception() {
        super();
    }
    
    public FaultType_Exception(String message) {
        super(message);
    }
    
    public FaultType_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public FaultType_Exception(String message, ar.com.zeni.zeniwsdl.FaultType faultType) {
        super(message);
        this.faultType = faultType;
    }

    public FaultType_Exception(String message, ar.com.zeni.zeniwsdl.FaultType faultType, Throwable cause) {
        super(message, cause);
        this.faultType = faultType;
    }

    public ar.com.zeni.zeniwsdl.FaultType getFaultInfo() {
        return this.faultType;
    }
}
