
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package ar.com.zeni.zeniwsdl;

import ar.com.zeni.implementation.ServiceImplementation;

/**
 * This class was generated by Apache CXF 2.6.1
 * 2014-08-25T12:42:58.873-03:00
 * Generated source version: 2.6.1
 * 
 */

@javax.jws.WebService(
                      serviceName = "ZeniWSDL",
                      portName = "ZeniWSDLSOAP",
                      targetNamespace = "http://www.zeni.com.ar/ZeniWSDL/",
                      wsdlLocation = "file:/home/rodrigo/Workers/Wespaces/Zenit-1.0.0.0/jaxzeniwsimpl/WebContent/wsdl/ZeniWSDL.wsdl",
                      endpointInterface = "ar.com.zeni.zeniwsdl.ZeniWSDL")
public class ZeniWSDLImpl extends ServiceImplementation implements ZeniWSDL {
}
