package ar.com.zeni.zeniwsdl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.6.1
 * 2015-01-13T18:15:06.126-03:00
 * Generated source version: 2.6.1
 * 
 */
@WebServiceClient(name = "ZeniWSDL", 
                  wsdlLocation = "file:/home/rodrigo/Workers/Wespaces/Zenit-1.0.0.0/jaxzeniwsimpl/WebContent/wsdl/ZeniWSDL.wsdl",
                  targetNamespace = "http://www.zeni.com.ar/ZeniWSDL/") 
public class ZeniWSDL_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.zeni.com.ar/ZeniWSDL/", "ZeniWSDL");
    public final static QName ZeniWSDLSOAP = new QName("http://www.zeni.com.ar/ZeniWSDL/", "ZeniWSDLSOAP");
    static {
        URL url = null;
        try {
            url = new URL("file:/home/rodrigo/Workers/Wespaces/Zenit-1.0.0.0/jaxzeniwsimpl/WebContent/wsdl/ZeniWSDL.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ZeniWSDL_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/home/rodrigo/Workers/Wespaces/Zenit-1.0.0.0/jaxzeniwsimpl/WebContent/wsdl/ZeniWSDL.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ZeniWSDL_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ZeniWSDL_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ZeniWSDL_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns ZeniWSDL
     */
    @WebEndpoint(name = "ZeniWSDLSOAP")
    public ZeniWSDL getZeniWSDLSOAP() {
        return super.getPort(ZeniWSDLSOAP, ZeniWSDL.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ZeniWSDL
     */
    @WebEndpoint(name = "ZeniWSDLSOAP")
    public ZeniWSDL getZeniWSDLSOAP(WebServiceFeature... features) {
        return super.getPort(ZeniWSDLSOAP, ZeniWSDL.class, features);
    }

}
